exports.SPORT_ID = {
    'sports': [
        {'sport': "Baseball", 'id': 1},
        {'sport': "Field Hockey", 'id': 2},
        {'sport': "Football", 'id': 3},
        {'sport': "Mens Basketball", 'id': 5},
        {'sport': "Mens Fencing", 'id': 7},
        {'sport': "Mens Golf", 'id': 8},
        {'sport': "Mens Gymnastics", 'id': 9},
        {'sport': "Mens Ice Hockey", 'id': 10},
        {'sport': "Mens Lacrosse", 'id': 11},
        {'sport': "Mens Soccer", 'id': 12},
        {'sport': "Mens Swimming and Diving", 'id': 13},
        {'sport': "Mens Tennis", 'id': 14},
        {'sport': "Mens Volleyball", 'id': 16},
        {'sport': "Softball", 'id': 17},
        {'sport': "Track and Field", 'id': 33},
        {'sport': "Womens Basketball", 'id': 18},
        {'sport': "Womens Fencing", 'id': 20},
        {'sport': "Womens Golf", 'id': 21},
        {'sport': "Womens Gymnastics", 'id': 22},
        {'sport': "Womens Ice Hockey", 'id': 23},
        {'sport': "Womens Lacrosse", 'id': 24},
        {'sport': "Womens Soccer", 'id': 25},
        {'sport': "Womens Swimming and Diving", 'id': 26},
        {'sport': "Womens Tennis", 'id': 27},
        {'sport': "Womens Volleyball", 'id': 29},
        {'sport': "Wrestling", 'id': 30},
        {'sport': "Cross Country", 'id': 31},
        {'sport': "Fencing", 'id': 32},
        {'sport': "Mens Rugby", 'id': 40},
        {'sport': "Womens Rugby", 'id': 45}]
};
