
//Bus routes with ID for API url. Missing downtown and south atherton football shuttles.
exports.BUS_ROUTE_ID = {
  "buses": [
    {"name": "Blue loop", "id": 55},
    {"name": "White Loop", "id": 57},
    {"name": "Red link", "id": 51},
    {"name": "Green link", "id": 53},
    {"name": "A", "id": 1},
    {"name": "B", "id": 4},
    {"name": "C", "id": 7},
    {"name": "F", "id": 10},
    {"name": "G", "id": 11},
    {"name":" HC", "id": 61},
    {"name":" HM", "id": 60},
    {"name": "K", "id": 16},
    {"name": "N", "id": 22},
    {"name": "NE", "id": 21},
    {"name": "NV", "id": 25},
    {"name": "R", "id": 31},
    {"name": "RC", "id": 33},
    {"name": "RP", "id": 34},
    {"name": "S", "id": 37},
    {"name": "UT", "id": 40},
    {"name": "V", "id": 43},
    {"name": "VE", "id": 42},
    {"name": "VN", "id": 44},
    {"name": "W", "id": 46},
    {"name": "WE", "id": 45},
    {"name": "XB", "id": 49},
    {"name":" XG", "id": 50}
  ]
};

exports.STOP_ID_TO_NAME = {
  'college_avenue_at_allen_street': {'name': 'E. College Ave at S. Allen Street', 'stopId': 1},
  'Burrowes_Rd_at_Deike_Building': {'name': 'Burrowes Rd at Deike Building', 'stopId': 2},
  'Burrowes_Rd_at_Waring_Commons': {'name': 'Burrowes Rd at Waring Commons', 'stopId': 3},
  'pattee_transit_center_eastbound': {'name': 'Pattee Transit Center Eastbound', 'stopId': 4},
  'north_atherton_street_at_hillcrest_ave': {'name': 'N Atherton St at Hillcrest Ave', 'stopId': 7},
  '1100_North_Atherton_CVS': {'name': '1101 N. Atherton St (CVS)', 'stopId': 8},
  '120_E_Clinton_Ave': {'name': '120 E Clinton Ave', 'stopId': 10},
  'Linn_St_at_E_North_Hills_Place': {'name': 'Linn St at E North Hills Place', 'stopId': 11},
  'Linn_St_at_E._Aaron_Dr_Outbound': {'name': 'Linn St at E. Aaron Dr (Outbound)', 'stopId': 12},
  '113_W_Aaron_Dr': {'name': '113 W Aaron Dr', 'stopId': 13},
  'W._Aaron_Dr_at_N._Atherton_St_Outbound': {'name': 'W. Aaron Dr at N. Atherton St (Outbound)', 'stopId': 14},
  '801_W_Aaron_Dr_Park_Forest_Apartments': {'name': '801 W Aaron Dr (Park Forest Apartments)', 'stopId': 15},
  '1003_W_Aaron_Dr_Copper_Beech': {'name': '1003 W Aaron Dr (Copper Beech)', 'stopId': 16},
  'Park_Ln_at_Park_Hills_Ave': {'name': 'Park Ln at Park Hills Ave', 'stopId': 17},
  'Princeton_Dr_at_Dogwood_Circle': {'name': 'Princeton Dr at Dogwood Circle', 'stopId': 18},
  'Princeton_Dr_at_Wiltshire_Dr': {'name': 'Princeton Dr at Wiltshire Dr', 'stopId': 20},
  'Devonshire_Drive_near_Wiltshire_Drive_inbound': {'name': 'Devonshire Drive near Wiltshire Drive Inbound', 'stopId': 21},
  'Wiltshire_Dr_at_Surry_Lane': {'name': 'Wiltshire Dr at Surry Lane', 'stopId': 22},
  'Wiltshire_Dr_at_Sierra_Lane': {'name': 'Wiltshire Dr at Sierra Lane', 'stopId': 23},
  'Devonshire_Drive_near_Wiltshire_Drive_Outbound': {'name': 'Devonshire Drive near Wiltshire Drive Outbound', 'stopId': 25},
  '464_Westgate_Dr': {'name': '464 Westgate Dr', 'stopId': 28},
  '530_Westgate_Dr': {'name': '530 Westgate Dr', 'stopId': 29},
  '694_Earl_Dr': {'name': '694 Earl Dr', 'stopId': 30},
  'Brittany_Drive_at_Lanceshire_Lane': {'name': 'Brittany Drive at Lanceshire Lane', 'stopId': 31},
  'Devonshire_at_Berkshire': {'name': 'Devonshire at Berkshire', 'stopId': 32},
  'Wiltshire_Dr_at_Princeton_Dr': {'name': 'Wiltshire Dr at Princeton Dr', 'stopId': 35},
  'Opposite_1637_Princeton_Dr': {'name': 'Opposite 1637 Princeton Dr', 'stopId': 36},
  'Opposite_1434_Park_Lane': {'name': 'Opposite 1434 Park Lane', 'stopId': 37},
  '1100_W_Aaron_Dr_Copper_Beech': {'name': '1100 W Aaron Dr (Copper Beech)', 'stopId': 39},
  '720_W_Aaron_Dr_Aaron_Village': {'name': '720 W Aaron Dr (Aaron Village)', 'stopId': 40},
  'W_Aaron_Dr_at_N_Atherton_St_Inbound': {'name': 'W Aaron Dr at N Atherton St Inbound', 'stopId': 41},
  '122_W_Aaron_Dr': {'name': '122 W Aaron Dr', 'stopId': 42},
  'E._Aaron_Dr_at_Linn_St_Inbound': {'name': 'E. Aaron Dr at Linn St (Inbound)', 'stopId': 43},
  'Linn_St_at_North_Hills_Place': {'name': 'Linn St at North Hills Place', 'stopId': 44},
  'E_Clinton_Ave_at_N_Allen_St': {'name': 'E Clinton Ave at N Allen St', 'stopId': 45},
  '1224_N_Atherton_St_-_Discovery_Space': {'name': '1224 N Atherton St - Discovery Space', 'stopId': 46},
  'N_Atherton_St_at_Mitchell_Ave_Inbound': {'name': 'N Atherton St at Mitchell Ave Inbound', 'stopId': 47},
  'Curtin_Rd_at_Pavilion_Theatre': {'name': 'Curtin Rd at Pavilion Theatre', 'stopId': 51},
  'E_College_Ave_at_Atherton_Hall': {'name': 'E College Ave at Atherton Hall', 'stopId': 52},
  'Bigler_Rd_at_Computer_Building': {'name': 'Bigler Rd at Computer Building', 'stopId': 53},
  'Shortlidge_Rd_at_White_Building': {'name': 'Shortlidge Rd at White Building', 'stopId': 54},
  'Pollock_Rd_at_Millennium_Science_Com': {'name': 'Pollock Rd at Millennium Science Com', 'stopId': 55},
  'N_Atherton_St_at_Walker_Building': {'name': 'N Atherton St at Walker Building', 'stopId': 285},
  'N_Atherton_St_at_Arbor_Way': {'name': 'N Atherton St at Arbor Way', 'stopId': 420},
  '595_Melissa_Lane': {'name': '595 Melissa Lane', 'stopId': 442},
  '603_Melissa_Lane': {'name': '603 Melissa Lane', 'stopId': 443},
  'Opposite_528_Melissa_Lane': {'name': 'Opposite 528 Melissa Lane', 'stopId': 446},
  'Canterbury_Drive_at_Oakley_Drive': {'name': 'Canterbury Drive at Oakley Drive', 'stopId': 447},
  'Canterbury_Drive_at_Bellvue_Circle': {'name': 'Canterbury Drive at Bellvue Circle', 'stopId': 449},
  '287_Douglas_Dr': {'name': '287 Douglas Dr', 'stopId': 451},
  'Douglas_Drive_at_School_Drive': {'name': 'Douglas Drive at School Drive', 'stopId': 453},
  '2108_N_Oak_Lane': {'name': '2108 N Oak Lane', 'stopId': 456},
  '2198_N_Oak_Lane': {'name': '2198 N Oak Lane', 'stopId': 457},
  'Galen_Drive_at_Kenley_Ct': {'name': 'Galen Drive at Kenley Ct', 'stopId': 459},
  'N_Atherton_St_at_E_Clinton_Ave': {'name': 'N Atherton St at E Clinton Ave', 'stopId': 527},
  'University_Dr_at_Bellaire_Ave_Outbound': {'name': 'University Dr at Bellaire Ave (Outbound)', 'stopId': 56},
  'University_Dr_at_E._Waring_AveOutbound': {'name': 'University Dr at E. Waring Ave(Outbound)', 'stopId': 57},
  'University_Dr_at_Easterly_Pkwy': {'name': 'University Dr at Easterly Pkwy', 'stopId': 58},
  'University_Dr_at_Legion_Ln': {'name': 'University Dr at Legion Ln', 'stopId': 59},
  'University_Dr_at_Nimitz_Ave_Outbound': {'name': 'University Dr at Nimitz Ave (Outbound)', 'stopId': 60},
  'University_Dr_at_Royal_Rd_Outbound': {'name': 'University Dr at Royal Rd (Outbound)', 'stopId': 61},
  '1602_University_Dr': {'name': '1602 University Dr', 'stopId': 62},
  '2390_S_Atherton_St_Meyer_Dairy': {'name': '2390 S Atherton St (Meyer Dairy)', 'stopId': 63},
  'S._Atherton_St_at_Hubler_Rd_Outbound': {'name': 'S. Atherton St at Hubler Rd (Outbound)', 'stopId': 65},
  'S_Atherton_St_at_Kennard_Rd': {'name': 'S Atherton St at Kennard Rd', 'stopId': 66},
  'Earlystown_Rd_PA_45_at_Ashworth_Lane': {'name': 'Earlystown Rd (PA 45) at Ashworth Lane', 'stopId': 80},
  'Earlystown_Rd_PA_45_at_Indian_Hill_Rd': {'name': 'Earlystown Rd (PA 45) at Indian Hill Rd', 'stopId': 81},
  'Earlystown_Rd_PA_45_at_Rockey_Lane': {'name': 'Earlystown Rd (PA 45) at Rockey Lane', 'stopId': 82},
  'Willowbrook_Dr_at_Estate_Dr': {'name': 'Willowbrook Dr at Estate Dr', 'stopId': 83},
  '1432_Willowbrook_Dr': {'name': '1432 Willowbrook Dr', 'stopId': 84},
  'Jacks_Mill_Dr_at_Elksview': {'name': 'Jacks Mill Dr at Elksview', 'stopId': 85},
  'Jacks_Mill_Dr_at_Centre_Estates': {'name': 'Jacks Mill Dr at Centre Estates', 'stopId': 89},
  '403_West_Dr': {'name': '403 West Dr', 'stopId': 90},
  'West_Dr_at_Homestead_LN': {'name': 'West Dr at Homestead LN', 'stopId': 91},
  'West_Dr_at_Torrey_Lane': {'name': 'West Dr at Torrey Lane', 'stopId': 92},
  'Torrey_Ln_at_Homestead_Ln': {'name': 'Torrey Ln at Homestead Ln', 'stopId': 93},
  'E_Main_St_at_N_Academy_St': {'name': 'E Main St at N Academy St', 'stopId': 94},
  'N_Church_St_at_Pine_St': {'name': 'N Church St at Pine St', 'stopId': 95},
  'Boalsburg_Pike_at_Lee_Ave_Inbound': {'name': 'Boalsburg Pike at Lee Ave (Inbound)', 'stopId': 96},
  'Boalsburg_Pike_at_KimportInbound': {'name': 'Boalsburg Pike at Kimport(Inbound)', 'stopId': 97},
  '224_Kimport_Ave': {'name': '224 Kimport Ave', 'stopId': 98},
  'Belle_Avenue_at_Ishler_Street': {'name': 'Belle Avenue at Ishler Street', 'stopId': 99},
  'Boalsburg_Pike_at_St._Josephs_school': {'name': 'Boalsburg Pike at St. Josephs school', 'stopId': 100},
  '121_Mary_Elizabeth_St': {'name': '121 Mary Elizabeth St', 'stopId': 101},
  'Warner_Blvd_at_Boalsburg_Med_Offices': {'name': 'Warner Blvd at Boalsburg Med Offices', 'stopId': 102},
  'S_Atherton_St_at_Circle_Dr': {'name': 'S Atherton St at Circle Dr', 'stopId': 103},
  'S_Atherton_St_at_Warnock_Rd': {'name': 'S Atherton St at Warnock Rd', 'stopId': 104},
  'S._Atherton_St_at_Hubler_Rd_Inbound': {'name': 'S. Atherton St at Hubler Rd (Inbound)', 'stopId': 105},
  'South_Atherton_Street_at_Scenery_Drive': {'name': 'South Atherton Street at Scenery Drive', 'stopId': 106},
  'University_Dr_at_Royal_Rd_Inbound': {'name': 'University Dr at Royal Rd (Inbound)', 'stopId': 107},
  'University_Dr_at_Nimitz_Ave_Inbound': {'name': 'University Dr at Nimitz Ave (Inbound)', 'stopId': 108},
  'University_Dr_at_Legion_Ln_Inbound': {'name': 'University Dr at Legion Ln (Inbound)', 'stopId': 109},
  '1001_University_Dr': {'name': '1001 University Dr', 'stopId': 110},
  'University_Dr_at_E._Waring_Ave_Inbound': {'name': 'University Dr at E. Waring Ave (Inbound)', 'stopId': 111},
  'University_Dr_at_Bellaire_Ave_Inbound': {'name': 'University Dr at Bellaire Ave (Inbound)', 'stopId': 112},
  'University_Dr_at_Lot_83_West': {'name': 'University Dr at Lot 83 West', 'stopId': 152},
  'University_Dr_at_Jordan_Center_Gate_D': {'name': 'University Dr at Jordan Center Gate D', 'stopId': 153},
  'Curtin_Rd_at_the_Intramural_Building': {'name': 'Curtin Rd at the Intramural Building', 'stopId': 154},
  'East_Halls_at_Curtin_Hall': {'name': 'East Halls at Curtin Hall', 'stopId': 155},
  'South_Atherton_at_Creekside_Plaza': {'name': 'South Atherton at Creekside Plaza', 'stopId': 156},
  '1661_S_Atherton_St_IHOP': {'name': '1661 S Atherton St (IHOP)', 'stopId': 157},
  'S_Ath_St_at_Rolling_Ridge_Dr_Inbound': {'name': 'S Ath St at Rolling Ridge Dr Inbound', 'stopId': 158},
  '3604_South_Atherton_T_and_B_Medical': {'name': '3604 South Atherton (T and B Medical)', 'stopId': 168},
  'South_Atherton_at_Villa_Crest_Drive': {'name': 'South Atherton at Villa Crest Drive', 'stopId': 172},
  'Curtin_Rd_at_Visual_Arts_Building': {'name': 'Curtin Rd at Visual Arts Building', 'stopId': 356},
  'Pattee_Transit_Center_Westbound': {'name': 'Pattee Transit Center Westbound', 'stopId': 357},
  'Burrowes_Rd_at_Rec_Hall': {'name': 'Burrowes Rd at Rec Hall', 'stopId': 358},
  'Burrowes_Road_at_Westgate_Building': {'name': 'Burrowes Road at Westgate Building', 'stopId': 359},
  'S_Burrowes_St_at_the_James_Elliott_Bldg': {'name': 'S Burrowes St at the James Elliott Bldg', 'stopId': 360},
  'Beaver_Ave_at_Schlow_Library/CATA_Office': {'name': 'Beaver Ave at Schlow Library/CATA Office', 'stopId': 361},
  'Boal_Avenue_Bus_322_at_Pine_Alley': {'name': 'Boal Avenue (Bus 322) at Pine Alley', 'stopId': 515},
  'Beacon_Circle_at_the_Club_House': {'name': 'Beacon Circle at the Club House', 'stopId': 533},
  'Beacon_Circle_at_Plymouth_Drive': {'name': 'Beacon Circle at Plymouth Drive', 'stopId': 535},
  'University_Drive_ramp_at_The_Meridian': {'name': 'University Drive ramp at The Meridian', 'stopId': 563},
  'E_Beaver_Ave_at_Calder_Commons': {'name': 'E Beaver Ave at Calder Commons', 'stopId': 564},
  'E_Beaver_Ave_at_Beaver_Hill_Apts': {'name': 'E Beaver Ave at Beaver Hill Apts', 'stopId': 565},
  'S_Ath_St_at_Rolling_Ridge_Dr_Outbound': {'name': 'S Ath St at Rolling Ridge Dr Outbound', 'stopId': 697},
  'Torrey_Lane_at_Loop_Rd': {'name': 'Torrey Lane at Loop Rd', 'stopId': 699},
  'Beacon_Circle_near_Belle_Avenue': {'name': 'Beacon Circle near Belle Avenue', 'stopId': 735},
  'Kimport_Ave_at_Belle_Ave_Inbound': {'name': 'Kimport Ave at Belle Ave Inbound', 'stopId': 748},
  'Belle_Ave_at_Lamp_Post_Lane_Inbound': {'name': 'Belle Ave at Lamp Post Lane Inbound', 'stopId': 749},
  '1454/1456_Willowbrook_Dr': {'name': '1454/1456 Willowbrook Dr', 'stopId': 752},
  'Beacon_Circle_near_Founders_Court': {'name': 'Beacon Circle near Founders Court', 'stopId': 812},
  'Elks_Club_Road_at_Mountainview_CC': {'name': 'Elks Club Road at Mountainview CC', 'stopId': 823},
  '461_Gerald_St': {'name': '461 Gerald St', 'stopId': 113},
  '2448_Buchenhorst_Rd': {'name': '2448 Buchenhorst Rd', 'stopId': 114},
  'Buchenhorst_Rd_at_Shawn_Circle': {'name': 'Buchenhorst Rd at Shawn Circle', 'stopId': 115},
  '2536_Buchenhorst_Rd': {'name': '2536 Buchenhorst Rd', 'stopId': 116},
  '278_Gerald_St_Kids_Court_Child_Care': {'name': '278 Gerald St (Kids Court Child Care)', 'stopId': 117},
  'Trout_Road_at_Pleasant_Pointe': {'name': 'Trout Road at Pleasant Pointe', 'stopId': 118},
  'Opposite_620_Trout_Rd': {'name': 'Opposite 620 Trout Rd', 'stopId': 119},
  'Mountain_Laurel_Rd_at_Trout_Rd_Inbound': {'name': 'Mountain Laurel Rd at Trout Rd Inbound', 'stopId': 120},
  'Mossey_Glen_Rd_at_Fernleaf_Ct_Inbound': {'name': 'Mossey Glen Rd at Fernleaf Ct Inbound', 'stopId': 121},
  'October_Dr_at_Creekside_Dr_Inbound': {'name': 'October Dr at Creekside Dr Inbound', 'stopId': 122},
  '191_Creekside_Dr': {'name': '191 Creekside Dr', 'stopId': 123},
  'Creekside_Dr_at_Mitch_Ave_Inbound': {'name': 'Creekside Dr at Mitch Ave Inbound', 'stopId': 124},
  'Creekside_Dr_at_Fairlawn_Ave_Inbound': {'name': 'Creekside Dr at Fairlawn Ave Inbound', 'stopId': 125},
  '221_Fairlawn_Ave': {'name': '221 Fairlawn Ave', 'stopId': 126},
  '1233_Houserville_Rd': {'name': '1233 Houserville Rd', 'stopId': 127},
  'Puddintown_Rd_at_Meadow_Lane_Inbound': {'name': 'Puddintown Rd at Meadow Lane Inbound', 'stopId': 128},
  'Puddintown_Rd_at_Spring_Creek_Ln_Inbound': {'name': 'Puddintown Rd at Spring Creek Ln Inbound', 'stopId': 129},
  '366_Walker_Dr_Far_Back_Lot_Omega': {'name': '366 Walker Dr Far Back Lot (Omega)', 'stopId': 130},
  '270_Walker_Dr_Rear_Ent_PFG_Bldg': {'name': '270 Walker Dr Rear Ent (PFG Bldg)', 'stopId': 131},
  'Walker_Dr_at_Hawthorne_Dr_Inbound': {'name': 'Walker Dr at Hawthorne Dr Inbound', 'stopId': 132},
  'Walker_Dr_at_Hawthorne_Dr_Outbound': {'name': 'Walker Dr at Hawthorne Dr Outbound', 'stopId': 133},
  'Opp_270_Walker_Dr_Rear_Ent_PFG_Bldg': {'name': 'Opp 270 Walker Dr Rear Ent (PFG Bldg)', 'stopId': 134},
  'Opp_366_Walker_Dr_Far_Back_Lot_Omega': {'name': 'Opp 366 Walker Dr Far Back Lot (Omega)', 'stopId': 135},
  'Puddintown_Rd_at_Spring_Creek_Park': {'name': 'Puddintown Rd at Spring Creek Park', 'stopId': 136},
  'Puddintown_Rd_at_Meadow_Lane_Outbound': {'name': 'Puddintown Rd at Meadow Lane Outbound', 'stopId': 137},
  '1232_Houserville_Rd': {'name': '1232 Houserville Rd', 'stopId': 138},
  'Fairlawn_Ave_at_Kuhns_Lane': {'name': 'Fairlawn Ave at Kuhns Lane', 'stopId': 139},
  'Creekside_Dr_at_Fairlawn_Ave_Outbound': {'name': 'Creekside Dr at Fairlawn Ave Outbound', 'stopId': 140},
  'Creekside_Dr_at_Mitch_Ave_Outbound': {'name': 'Creekside Dr at Mitch Ave Outbound', 'stopId': 141},
  '192_Creekside_Dr': {'name': '192 Creekside Dr', 'stopId': 142},
  'October_Dr_at_Creekside_Dr_Outbound': {'name': 'October Dr at Creekside Dr Outbound', 'stopId': 143},
  'Mossey_Glen_Rd_at_Fernleaf_Ct_Outbound': {'name': 'Mossey Glen Rd at Fernleaf Ct Outbound', 'stopId': 144},
  'Mountain_Laurel_Rd_at_Trout_Rd_Outbound': {'name': 'Mountain Laurel Rd at Trout Rd Outbound', 'stopId': 145},
  '620_Trout_Rd': {'name': '620 Trout Rd', 'stopId': 146},
  'Gerald_St_at_Matthew_Circle_Outbound': {'name': 'Gerald St at Matthew Circle Outbound', 'stopId': 147},
  'Opposite_1031_E_College_Ave': {'name': 'Opposite 1031 E College Ave', 'stopId': 160},
  'E_College_Ave_at_Your_Building_Center': {'name': 'E College Ave at Your Building Center', 'stopId': 161},
  'E_College_Ave_at_Squirrel_Dr_Outbound': {'name': 'E College Ave at Squirrel Dr Outbound', 'stopId': 162},
  'E_College_Av_at_Hickeys': {'name': 'E College Av at Hickeys', 'stopId': 169},
  'E_College_Ave_at_Puddintown_Rd': {'name': 'E College Ave at Puddintown Rd', 'stopId': 170},
  '1031_East_College_Ave_Lettermans': {'name': '1031 East College Ave (Lettermans)', 'stopId': 171},
  'Dreibelbis_St_at_Shiloh_Rd': {'name': 'Dreibelbis St at Shiloh Rd', 'stopId': 323},
  'Dreibelbis_St_opp_Independence_Pl': {'name': 'Dreibelbis St opp Independence Pl', 'stopId': 325},
  'Dreibelbis_St_at_Lion_Country_Kia': {'name': 'Dreibelbis St at Lion Country Kia', 'stopId': 404},
  'Gerald_St_entrance_to_Lower_Penn_Hills': {'name': 'Gerald St entrance to Lower Penn Hills', 'stopId': 760},
  'Timothy_Lane_at_W_Blade_Dr': {'name': 'Timothy Lane at W Blade Dr', 'stopId': 173},
  'W_Blade_Dr_at_Gardener_Lane': {'name': 'W Blade Dr at Gardener Lane', 'stopId': 174},
  'Gardener_Lane_at_Whitehall_Rd': {'name': 'Gardener Lane at Whitehall Rd', 'stopId': 175},
  '4805_Whitehall_Rd': {'name': '4805 Whitehall Rd', 'stopId': 176},
  'Whitehall_Rd_at_Fairbrook_Dr_Outbound': {'name': 'Whitehall Rd at Fairbrook Dr Outbound', 'stopId': 177},
  'Whitehall_Rd_at_Fairbrook_Dr_Inbound': {'name': 'Whitehall Rd at Fairbrook Dr Inbound', 'stopId': 178},
  'Opposite_4300_Whitehall_Rd': {'name': 'Opposite 4300 Whitehall Rd', 'stopId': 179},
  'Tadpole_Rd_at_Whitehall_Rd': {'name': 'Tadpole Rd at Whitehall Rd', 'stopId': 180},
  'Tadpole_Rd_at_Elm_Rd': {'name': 'Tadpole Rd at Elm Rd', 'stopId': 181},
  'Opposite_1281_Tadpole_Rd': {'name': 'Opposite 1281 Tadpole Rd', 'stopId': 182},
  'Tadpole_Rd_at_Oak_Glen_Rd_Inbound': {'name': 'Tadpole Rd at Oak Glen Rd Inbound', 'stopId': 183},
  'Tadpole_Rd_at_Oak_Glen_Rd_Outbound': {'name': 'Tadpole Rd at Oak Glen Rd Outbound', 'stopId': 184},
  'Tadpole_Rd_at_W_Pine_Grove_Rd_Inbound': {'name': 'Tadpole Rd at W Pine Grove Rd Inbound', 'stopId': 185},
  'Tadpole_Rd_at_W_Pine_Grove_Rd_Outbound': {'name': 'Tadpole Rd at W Pine Grove Rd Outbound', 'stopId': 186},
  'W_Pine_Grove_Rd_at_Ross_St_Inbound': {'name': 'W Pine Grove Rd at Ross St Inbound', 'stopId': 187},
  'W_Pine_Grove_Rd_at_Ross_St_Outbound': {'name': 'W Pine Grove Rd at Ross St Outbound', 'stopId': 188},
  'W_Pine_Grove_Rd_at_Wyoming_Ave_Inbound': {'name': 'W Pine Grove Rd at Wyoming Ave Inbound', 'stopId': 189},
  'W_Pine_Grove_Rd_at_Wyoming_Ave_Outbound': {'name': 'W Pine Grove Rd at Wyoming Ave Outbound', 'stopId': 190},
  'Pine_Grove_Rd_at_Plainfield_Dr_Outbound': {'name': 'Pine Grove Rd at Plainfield Dr Outbound', 'stopId': 191},
  'Pine_Grove_Rd_at_Plainfield_Dr_Inbound': {'name': 'Pine Grove Rd at Plainfield Dr Inbound', 'stopId': 192},
  '347_W_Pine_Grove_Rd': {'name': '347 W Pine Grove Rd', 'stopId': 193},
  '290_W_Pine_Grove_Rd': {'name': '290 W Pine Grove Rd', 'stopId': 194},
  'W_Pine_Grove_Rd_at_Deepwood_Dr_Inbound': {'name': 'W Pine Grove Rd at Deepwood Dr Inbound', 'stopId': 195},
  'W_Pine_Grove_Rd_at_Deepwood_Dr_Outbound': {'name': 'W Pine Grove Rd at Deepwood Dr Outbound', 'stopId': 196},
  'W_Pine_Grove_Rd_at_Sports_Rd': {'name': 'W Pine Grove Rd at Sports Rd', 'stopId': 197},
  'W_Pine_Grove_Rd_at_Mayes_St': {'name': 'W Pine Grove Rd at Mayes St', 'stopId': 198},
  'E_Pine_Grove_Rd_at_Nixon_Rd': {'name': 'E Pine Grove Rd at Nixon Rd', 'stopId': 199},
  '116_E_Pine_Grove_Rd_Post_Office': {'name': '116 E Pine Grove Rd (Post Office)', 'stopId': 200},
  '226_E_Pine_Grove_Rd': {'name': '226 E Pine Grove Rd', 'stopId': 201},
  '229_E_Pine_Grove_Rd': {'name': '229 E Pine Grove Rd', 'stopId': 202},
  'E_Pine_Grove_Rd_at_Rosemont_Dr_Outbound': {'name': 'E Pine Grove Rd at Rosemont Dr Outbound', 'stopId': 203},
  'E_Pine_Grove_Rd_at_Rosemont_Dr_Inbound': {'name': 'E Pine Grove Rd at Rosemont Dr Inbound', 'stopId': 204},
  'E_Pine_Grove_Rd_at_Meckley_Rd': {'name': 'E Pine Grove Rd at Meckley Rd', 'stopId': 205},
  'E_Pine_Grove_Rd_at_Banyan_Dr': {'name': 'E Pine Grove Rd at Banyan Dr', 'stopId': 206},
  'Opposite_3450_W_College_Ave': {'name': 'Opposite 3450 W College Ave', 'stopId': 207},
  '3490_W_College_Ave': {'name': '3490 W College Ave', 'stopId': 208},
  'Opposite_3220_W_College_Ave': {'name': 'Opposite 3220 W College Ave', 'stopId': 209},
  '3220_W_College_AveState_College_Motors': {'name': '3220 W College Ave(State College Motors)', 'stopId': 210},
  'W_Whitehall_Rd_near_Research_Dr': {'name': 'W Whitehall Rd near Research Dr', 'stopId': 211},
  'W_Whitehall_Road_at_CATA': {'name': 'W Whitehall Road at CATA', 'stopId': 212},
  '3106_Stonebridge_Dr': {'name': '3106 Stonebridge Dr', 'stopId': 213},
  'Opposite_3098_Stonebridge_Dr': {'name': 'Opposite 3098 Stonebridge Dr', 'stopId': 214},
  'Stonebridge_Dr_at_James_Ave_Outbound': {'name': 'Stonebridge Dr at James Ave Outbound', 'stopId': 215},
  'Stonebridge_Dr_at_James_Ave_Inbound': {'name': 'Stonebridge Dr at James Ave Inbound', 'stopId': 216},
  '1680_Bristol_-_Stonebridge_Senior_Apts': {'name': '1680 Bristol - Stonebridge Senior Apts', 'stopId': 217},
  '1631_Bristol_Ave': {'name': '1631 Bristol Ave', 'stopId': 218},
  'Blue_Course_Dr_at_Shellers_Bend_Inbound': {'name': 'Blue Course Dr at Shellers Bend Inbound', 'stopId': 219},
  'Blue_Course_Dr_at_Shellers_Bend_Outbound': {'name': 'Blue Course Dr at Shellers Bend Outbound', 'stopId': 220},
  'Blue_Course_Dr_at_Wells_Terrace_Inbound': {'name': 'Blue Course Dr at Wells Terrace Inbound', 'stopId': 221},
  'Blue_Course_Dr_at_Wells_Terrace_Outbound': {'name': 'Blue Course Dr at Wells Terrace Outbound', 'stopId': 222},
  'Bayberry_Dr_at_Grace_St_Inbound': {'name': 'Bayberry Dr at Grace St Inbound', 'stopId': 223},
  'Bayberry_Dr_at_Grace_St_Outbound': {'name': 'Bayberry Dr at Grace St Outbound', 'stopId': 224},
  'Bayberry_Dr_at_Saxton_Dr_Inbound': {'name': 'Bayberry Dr at Saxton Dr Inbound', 'stopId': 225},
  'Bayberry_Dr_at_Saxton_Dr_Outbound': {'name': 'Bayberry Dr at Saxton Dr Outbound', 'stopId': 226},
  'Bayberry_Dr_at_Barley_Way_Outbound': {'name': 'Bayberry Dr at Barley Way Outbound', 'stopId': 227},
  'Bayberry_Dr_at_Barley_Way_Inbound': {'name': 'Bayberry Dr at Barley Way Inbound', 'stopId': 228},
  '854_Bayberry_Dr': {'name': '854 Bayberry Dr', 'stopId': 229},
  '853_Bayberry_Dr': {'name': '853 Bayberry Dr', 'stopId': 230},
  '816_Bayberry_Dr': {'name': '816 Bayberry Dr', 'stopId': 231},
  '811_Bayberry_Dr': {'name': '811 Bayberry Dr', 'stopId': 232},
  '817_Saxton_Dr': {'name': '817 Saxton Dr', 'stopId': 233},
  'Opposite_817_Saxton_Dr': {'name': 'Opposite 817 Saxton Dr', 'stopId': 234},
  '757_Westerly_Pkwy': {'name': '757 Westerly Pkwy', 'stopId': 235},
  '768_Westerly_Pkwy': {'name': '768 Westerly Pkwy', 'stopId': 236},
  'S_Sparks_St_at_Westerly_Pkwy_Outbound': {'name': 'S Sparks St at Westerly Pkwy Outbound', 'stopId': 237},
  'S_Sparks_St_at_Westerly_Pkwy_Inbound': {'name': 'S Sparks St at Westerly Pkwy Inbound', 'stopId': 238},
  'S_Sparks_St_at_W_Prospect_Ave_Outbound': {'name': 'S Sparks St at W Prospect Ave Outbound', 'stopId': 239},
  'S_Sparks_St_at_W_Prospect_Ave_Inbound': {'name': 'S Sparks St at W Prospect Ave Inbound', 'stopId': 240},
  'S_Sparks_St_at_W_Nittany_Ave_Inbound': {'name': 'S Sparks St at W Nittany Ave Inbound', 'stopId': 241},
  'S_Sparks_St_at_W_Nittany_Ave_Outbound': {'name': 'S Sparks St at W Nittany Ave Outbound', 'stopId': 242},
  '218_S_Sparks_St': {'name': '218 S Sparks St', 'stopId': 243},
  '219_S_Sparks_St': {'name': '219 S Sparks St', 'stopId': 244},
  'S_Sparks_St_at_Calder_Way': {'name': 'S Sparks St at Calder Way', 'stopId': 245},
  'W_Beaver_Ave_at_S_Barnard_St': {'name': 'W Beaver Ave at S Barnard St', 'stopId': 246},
  'W_College_Ave_at_N_Barnard_St': {'name': 'W College Ave at N Barnard St', 'stopId': 247},
  'South_Burrowes_St_at_Calder_Way': {'name': 'South Burrowes St at Calder Way', 'stopId': 248},
  '4802_Whitehall_Rd': {'name': '4802 Whitehall Rd', 'stopId': 702},
  '904_West_Pine_Grove_Road': {'name': '904 West Pine Grove Road', 'stopId': 765},
  'opposite_904_West_Pine_Grove_Road': {'name': 'opposite 904 West Pine Grove Road', 'stopId': 769},
  '1060_Pine_Grove_Rd': {'name': '1060 Pine Grove Rd', 'stopId': 828},
  'Opposite_1060_Pine_Grove_Rd': {'name': 'Opposite 1060 Pine Grove Rd', 'stopId': 829},
  'Whitehall_Rd_at_Ramblewood_Road': {'name': 'Whitehall Rd at Ramblewood Road', 'stopId': 843},
  'Whitehall_Rd_opposite_Ramblewood_Road': {'name': 'Whitehall Rd opposite Ramblewood Road', 'stopId': 854},
  '1019_Ghaner_Road_Happy_Valley_Ortho.': {'name': '1019 Ghaner Road (Happy Valley Ortho.)', 'stopId': 26},
  'opposite_1019_Ghaner_Road': {'name': 'opposite 1019 Ghaner Road', 'stopId': 33},
  '1120_Halfmoon_Valley_Road': {'name': '1120 Halfmoon Valley Road', 'stopId': 419},
  'Valley_Vista_Dr_Opp_Lowes_Center': {'name': 'Valley Vista Dr Opp Lowes Center', 'stopId': 469},
  'Valley_Vista_Drive_at_Lowes_Center': {'name': 'Valley Vista Drive at Lowes Center', 'stopId': 470},
  'N_Atherton_St_at_Douglas_Dr': {'name': 'N Atherton St at Douglas Dr', 'stopId': 471},
  'N_Atherton_St_at_Hawbaker_Industrial_Dr': {'name': 'N Atherton St at Hawbaker Industrial Dr', 'stopId': 472},
  'N_Atherton_St_at_Fairwood_Lane': {'name': 'N Atherton St at Fairwood Lane', 'stopId': 473},
  'N_Atherton_St_near_Fairfield_Inn': {'name': 'N Atherton St near Fairfield Inn', 'stopId': 474},
  '1870_North_Atherton_Street': {'name': '1870 North Atherton Street', 'stopId': 498},
  'N_Atherton_St_at_Chick-Fil-A': {'name': 'N Atherton St at Chick-Fil-A', 'stopId': 499},
  'N_Atherton_St_at_Colonnade_Blvd': {'name': 'N Atherton St at Colonnade Blvd', 'stopId': 500},
  'across_from_1120_Halfmoon_Valley_Rd': {'name': 'across from 1120 Halfmoon Valley Rd', 'stopId': 505},
  '1611_North_Atheron_Champs': {'name': '1611 North Atheron (Champs)', 'stopId': 522},
  '1450_N_Atherton_St_at_Hoss': {'name': '1450 N Atherton St at Hoss', 'stopId': 523},
  'N_Atherton_St_at_Denton_Ave': {'name': 'N Atherton St at Denton Ave', 'stopId': 524},
  'N_Atherton_St_at_N_Hills_Place_Inbound': {'name': 'N Atherton St at N Hills Place Inbound', 'stopId': 525},
  'N_Atherton_St_at_N_Hills_Place_Outbound': {'name': 'N Atherton St at N Hills Place Outbound', 'stopId': 526},
  '216_Carnegie_Drive': {'name': '216 Carnegie Drive', 'stopId': 558},
  '3181_Carnegie_Drive': {'name': '3181 Carnegie Drive', 'stopId': 568},
  '1612_N_Atherton_St_KBB_Realtors': {'name': '1612 N Atherton St (KBB Realtors)', 'stopId': 705},
  'Grays_Woods_Blvd_at_Red_Alder_Rd_Inbound': {'name': 'Grays Woods Blvd at Red Alder Rd Inbound', 'stopId': 733},
  'Grays_Woods_Blvd_at_Red_Alder_Rd_Outbnd': {'name': 'Grays Woods Blvd at Red Alder Rd Outbnd', 'stopId': 734},
  'Grays_Woods_Blvd_at_Cherrywood_Rd_Inbnd': {'name': 'Grays Woods Blvd at Cherrywood Rd Inbnd', 'stopId': 736},
  'Grays_Woods_Blvd_at_Cherrywood_Rd_Outbnd': {'name': 'Grays Woods Blvd at Cherrywood Rd Outbnd', 'stopId': 737},
  'Ghaner_Rd_at_Welty_Lane_Inbound': {'name': 'Ghaner Rd at Welty Lane Inbound', 'stopId': 739},
  'Ghaner_Rd_at_Welty_Lane_Outbound': {'name': 'Ghaner Rd at Welty Lane Outbound', 'stopId': 740},
  'Ghaner_Rd_at_Ghaner_Dr_Inbound': {'name': 'Ghaner Rd at Ghaner Dr Inbound', 'stopId': 741},
  'Ghaner_Rd_at_Ghaner_Dr_Outbound': {'name': 'Ghaner Rd at Ghaner Dr Outbound', 'stopId': 742},
  'Carnegie_Dr_at_Ghaner_Dr_Inbound': {'name': 'Carnegie Dr at Ghaner Dr Inbound', 'stopId': 743},
  'Carnegie_Dr_at_Ghaner_Dr_Outbound': {'name': 'Carnegie Dr at Ghaner Dr Outbound', 'stopId': 744},
  'N_Atherton_St_at_Northwest_Bank': {'name': 'N Atherton St at Northwest Bank', 'stopId': 766},
  'N_Atherton_St_across_from_Sheetz': {'name': 'N Atherton St across from Sheetz', 'stopId': 767},
  'Meeks_Lane_at_Sellers_Lane': {'name': 'Meeks Lane at Sellers Lane', 'stopId': 770},
  'Meeks_Lane_at_Heiskel_Dr': {'name': 'Meeks Lane at Heiskel Dr', 'stopId': 771},
  'Halfmoon_Valley_Rd_at_Grays_Church': {'name': 'Halfmoon Valley Rd at Grays Church', 'stopId': 772},
  'Halfmoon_Valley_Rd_at_Granny_Lane': {'name': 'Halfmoon Valley Rd at Granny Lane', 'stopId': 773},
  'Halfmoon_Valley_Rd_opposite_Brothers': {'name': 'Halfmoon Valley Rd opposite Brothers', 'stopId': 774},
  'Halfmoon_Valley_Rd_at_Municipal_Lane': {'name': 'Halfmoon Valley Rd at Municipal Lane', 'stopId': 775},
  'Halfmoon_Valley_Rd_opposite_Ira_Lane': {'name': 'Halfmoon Valley Rd opposite Ira Lane', 'stopId': 776},
  'Halfmoon_Valley_Rd_at_Way_Farm': {'name': 'Halfmoon Valley Rd at Way Farm', 'stopId': 777},
  'Smith_Rd_at_Centennial_Hills_Rd': {'name': 'Smith Rd at Centennial Hills Rd', 'stopId': 778},
  'Smith_Rd_at_Buckhorn_Rd': {'name': 'Smith Rd at Buckhorn Rd', 'stopId': 779},
  'Smith_Rd_at_Autumn_Circle': {'name': 'Smith Rd at Autumn Circle', 'stopId': 780},
  'Lutz_Lane_at_Shanelly_Dr': {'name': 'Lutz Lane at Shanelly Dr', 'stopId': 781},
  'Lutz_Lane_at_Ira_Lane': {'name': 'Lutz Lane at Ira Lane', 'stopId': 782},
  'Lutz_Lane_at_Smith_Rd': {'name': 'Lutz Lane at Smith Rd', 'stopId': 783},
  'Smith_Rd_at_Lutz_Lane': {'name': 'Smith Rd at Lutz Lane', 'stopId': 784},
  'Lutz_Lane_opposite_Ira_Lane': {'name': 'Lutz Lane opposite Ira Lane', 'stopId': 785},
  'Lutz_Lane_opposite_Shanelly_Dr': {'name': 'Lutz Lane opposite Shanelly Dr', 'stopId': 786},
  'Smith_Rd_opposite_Autumn_Circle': {'name': 'Smith Rd opposite Autumn Circle', 'stopId': 787},
  'Smith_Rd_opposite_Buckhorn_Rd': {'name': 'Smith Rd opposite Buckhorn Rd', 'stopId': 788},
  'Smith_Rd_at_Marengo_Rd': {'name': 'Smith Rd at Marengo Rd', 'stopId': 789},
  'Halfmoon_Valley_Rd_opposite_Way_Farm': {'name': 'Halfmoon Valley Rd opposite Way Farm', 'stopId': 790},
  'Halfmoon_Valley_Rd_at_Ira_Lane': {'name': 'Halfmoon Valley Rd at Ira Lane', 'stopId': 791},
  'Halfmoon_Valley_Rd_at_Houtz_Lane': {'name': 'Halfmoon Valley Rd at Houtz Lane', 'stopId': 792},
  'Halfmoon_Valley_Rd_at_Brothers_Pizza': {'name': 'Halfmoon Valley Rd at Brothers Pizza', 'stopId': 793},
  'Halfmoon_Valley_Rd_at_Sawmill_Rd': {'name': 'Halfmoon Valley Rd at Sawmill Rd', 'stopId': 794},
  'Halfmoon_Valley_Rd_at_Deerbrook_Dr': {'name': 'Halfmoon Valley Rd at Deerbrook Dr', 'stopId': 795},
  'Meeks_Lane_opposite_Heiskel_Dr': {'name': 'Meeks Lane opposite Heiskel Dr', 'stopId': 796},
  'Meeks_Lane_opposite_Sellers_Lane': {'name': 'Meeks Lane opposite Sellers Lane', 'stopId': 797},
  'Halfmoon_Valley_Rd_at_Marengo_Rd': {'name': 'Halfmoon Valley Rd at Marengo Rd', 'stopId': 798},
  'Marengo_Rd_at_Halfmoon_Valley_Rd': {'name': 'Marengo Rd at Halfmoon Valley Rd', 'stopId': 799},
  'Charlotte_St_at_Lutz_Lane': {'name': 'Charlotte St at Lutz Lane', 'stopId': 800},
  'Lutz_Lane_at_Charlotte_St': {'name': 'Lutz Lane at Charlotte St', 'stopId': 801},
  'North_Athernton_St_at_Galen_Dr': {'name': 'North Athernton St at Galen Dr', 'stopId': 802},
  'Smiths_Rd_at_Buffalo_Lane': {'name': 'Smiths Rd at Buffalo Lane', 'stopId': 803},
  'Smith_Rd_at_Sky_Harbor_Lane': {'name': 'Smith Rd at Sky Harbor Lane', 'stopId': 804},
  'Meeks_Lane_at_Blackberry_Hill': {'name': 'Meeks Lane at Blackberry Hill', 'stopId': 805},
  'Meeks_Lane_opposite_Blackberry_Hill': {'name': 'Meeks Lane opposite Blackberry Hill', 'stopId': 806},
  'Grays_Woods_Blvd_at_Scotia_Rd_Outbound': {'name': 'Grays Woods Blvd at Scotia Rd (Outbound)', 'stopId': 807},
  'Grays_Woods_Blvd_at_Scotia_Rd_Inbound': {'name': 'Grays Woods Blvd at Scotia Rd (Inbound)', 'stopId': 808},
  'Smith_Rd_at_Tow_Hill_Rd': {'name': 'Smith Rd at Tow Hill Rd', 'stopId': 810},
  'Smith_Rd_near_Blue_Spruce_St': {'name': 'Smith Rd near Blue Spruce St', 'stopId': 811},
  'Lutz_Lane_at_Fay_Circle': {'name': 'Lutz Lane at Fay Circle', 'stopId': 814},
  'Standing_Ovation_Equestrian_Centre': {'name': 'Standing Ovation Equestrian Centre', 'stopId': 815},
  'oppsite_Standing_Ovation_Equestrian_Cent': {'name': 'oppsite Standing Ovation Equestrian Cent', 'stopId': 816},
  'Lutz_Lane_across_from_Fay_Circle': {'name': 'Lutz Lane across from Fay Circle', 'stopId': 821},
  'Smith_Rd_at_Red_Pine_St': {'name': 'Smith Rd at Red Pine St', 'stopId': 826},
  'Smith_Rd_at_Morris_Rd': {'name': 'Smith Rd at Morris Rd', 'stopId': 827},
  '5932_Buffalo_Run_Road': {'name': '5932 Buffalo Run Road', 'stopId': 844},
  'across_from_5932_Buffalo_Run_Road': {'name': 'across from 5932 Buffalo Run Road', 'stopId': 845},
  'Halfmoon_Valley_Road_at_Saddle_Ridge_Roa': {'name': 'Halfmoon Valley Road at Saddle Ridge Roa', 'stopId': 846},
  'Halfmoon_Valley_Road_opp_Saddle_Ridge_Rd': {'name': 'Halfmoon Valley Road opp Saddle Ridge Rd', 'stopId': 847},
  'W_College_Ave_at_N_Sparks_St': {'name': 'W College Ave at N Sparks St', 'stopId': 288},
  'W_Beaver_Ave_at_S_Sparks_St': {'name': 'W Beaver Ave at S Sparks St', 'stopId': 289},
  'W_College_Ave_at_N_Butz_St': {'name': 'W College Ave at N Butz St', 'stopId': 290},
  'W_College_Ave_at_Buckhout_St': {'name': 'W College Ave at Buckhout St', 'stopId': 291},
  'W_College_Ave_near_Corl_St': {'name': 'W College Ave near Corl St', 'stopId': 292},
  'W_College_Ave_at_Hoy_St': {'name': 'W College Ave at Hoy St', 'stopId': 293},
  '1445_W_College_Ave': {'name': '1445 W College Ave', 'stopId': 294},
  '1400_W_College_Ave': {'name': '1400 W College Ave', 'stopId': 295},
  'Opposite_1506_W_College_Ave': {'name': 'Opposite 1506 W College Ave', 'stopId': 296},
  '1506_W_College_Ave': {'name': '1506 W College Ave', 'stopId': 297},
  '2110_W_College_Ave': {'name': '2110 W College Ave', 'stopId': 302},
  '2111_W_College_Ave': {'name': '2111 W College Ave', 'stopId': 303},
  'W_College_Ave_at_Holly_Circle_Inbound': {'name': 'W College Ave at Holly Circle Inbound', 'stopId': 304},
  'W_College_Ave_at_Chelsea_Lane_Inbound': {'name': 'W College Ave at Chelsea Lane Inbound', 'stopId': 305},
  'W_College_Ave_at_Chelsea_Lane_Outbound': {'name': 'W College Ave at Chelsea Lane Outbound', 'stopId': 306},
  'W_College_Ave_at_Bristol_Ave_Inbound': {'name': 'W College Ave at Bristol Ave Inbound', 'stopId': 307},
  'W_College_Ave_at_Bristol_Ave_Outbound': {'name': 'W College Ave at Bristol Ave Outbound', 'stopId': 308},
  'Enterprise_Dr_at_Bristol_Ave': {'name': 'Enterprise Dr at Bristol Ave', 'stopId': 310},
  'Opposite_3035_Enterprise_Dr': {'name': 'Opposite 3035 Enterprise Dr', 'stopId': 312},
  '3075_Enterprise_Drive': {'name': '3075 Enterprise Drive', 'stopId': 313},
  'Enterprise_Dr_at_Cato_Ave': {'name': 'Enterprise Dr at Cato Ave', 'stopId': 314},
  'Cato_Ave_at_Enterprise_Dr': {'name': 'Cato Ave at Enterprise Dr', 'stopId': 315},
  'Cato_Ave_at_Research_Dr': {'name': 'Cato Ave at Research Dr', 'stopId': 316},
  'Research_Drive_at_CATA': {'name': 'Research Drive at CATA', 'stopId': 400},
  'W_College_Ave_at_Holly_Circle_Outbound': {'name': 'W College Ave at Holly Circle Outbound', 'stopId': 538},
  'Science_Park_Rd_at_Pine_Hall_Rd': {'name': 'Science Park Rd at Pine Hall Rd', 'stopId': 549},
  'Science_Park_Rd_at_Torron_Group': {'name': 'Science Park Rd at Torron Group', 'stopId': 550},
  '301_Science_Park_Rd_ARL_West_IV': {'name': '301 Science Park Rd (ARL West IV)', 'stopId': 551},
  '300_Science_Park_Rd_PSU_Tech_Support': {'name': '300 Science Park Rd (PSU Tech Support)', 'stopId': 552},
  '3054_Enterprise_Drive': {'name': '3054 Enterprise Drive', 'stopId': 768},
  'Science_Park_Rd_at_the_ARL_Building': {'name': 'Science Park Rd at the ARL Building', 'stopId': 813},
  'across_from_1700_Old_Gatesburg_Rd.': {'name': 'across from 1700 Old Gatesburg Rd.', 'stopId': 837},
  'Old_Gatesburg_Rd_near_Science_Pk_Red_OB': {'name': 'Old Gatesburg Rd near Science Pk Red OB', 'stopId': 838},
  'Opposite_225_Science_Park_Rd_ARL_Bldg': {'name': 'Opposite 225 Science Park Rd (ARL Bldg)', 'stopId': 839},
  '1700_Old_Gatesburg_Rd_-_Blue_Course_Med.': {'name': '1700 Old Gatesburg Rd - Blue Course Med.', 'stopId': 840},
  'Old_Gatesburg_Rd_near_Science_PK_IB': {'name': 'Old Gatesburg Rd near Science PK IB', 'stopId': 841},
  'Blue_Course_Dr_near_West_College_Ave': {'name': 'Blue Course Dr near West College Ave', 'stopId': 848},
  '1610_West_College_Ave_Waffle_Shop': {'name': '1610 West College Ave (Waffle Shop)', 'stopId': 849},
  'West_Park_Ave_at_North_Burrowes_St': {'name': 'West Park Ave at North Burrowes St', 'stopId': 6},
  'Martin_St_at_Park_Crest_Lane_Inbound': {'name': 'Martin St at Park Crest Lane Inbound', 'stopId': 477},
  'Martin_St_at_Park_Crest_Lane_Outbound': {'name': 'Martin St at Park Crest Lane Outbound', 'stopId': 478},
  '1400_Martin_St_Parkcrest_Terrace': {'name': '1400 Martin St (Parkcrest Terrace)', 'stopId': 479},
  'Opposite_1400_Martin_St': {'name': 'Opposite 1400 Martin St', 'stopId': 480},
  'Martin_Street_at_Herman_Drive': {'name': 'Martin Street at Herman Drive', 'stopId': 481},
  '1471_Martin_St_Weis': {'name': '1471 Martin St (Weis)', 'stopId': 482},
  '1521_Martin_St_Northland_Bowl': {'name': '1521 Martin St (Northland Bowl)', 'stopId': 484},
  'Park_Lane_at_Aaron_Dr': {'name': 'Park Lane at Aaron Dr', 'stopId': 485},
  'Park_Lane_at_Devonshire_Dr': {'name': 'Park Lane at Devonshire Dr', 'stopId': 486},
  'Park_Lane_at_Cornwall_Rd_Inbound': {'name': 'Park Lane at Cornwall Rd Inbound', 'stopId': 487},
  'Park_Lane_at_Cornwall_Rd_Outbound': {'name': 'Park Lane at Cornwall Rd Outbound', 'stopId': 488},
  'Park_Lane_at_Sierra_Lane': {'name': 'Park Lane at Sierra Lane', 'stopId': 489},
  'Park_Lane_at_Shannon_Lane': {'name': 'Park Lane at Shannon Lane', 'stopId': 490},
  'Park_Lane_at_Park_Forest_Ave_Inbound': {'name': 'Park Lane at Park Forest Ave Inbound', 'stopId': 491},
  'Park_Lane_at_Park_Forest_Ave_Outbound': {'name': 'Park Lane at Park Forest Ave Outbound', 'stopId': 492},
  'Park_Forest_Ave_at_Northbrook_Greens': {'name': 'Park Forest Ave at Northbrook Greens', 'stopId': 493},
  'Park_Forest_Ave_Opposite_Northbrook': {'name': 'Park Forest Ave Opposite Northbrook', 'stopId': 494},
  'Park_Forest_Ave_at_N_Atherton_Outbound': {'name': 'Park Forest Ave at N Atherton Outbound', 'stopId': 495},
  'Park_Forest_Ave_at_N_Atherton_Inbound': {'name': 'Park Forest Ave at N Atherton Inbound', 'stopId': 496},
  'Trader_Joes_Plaza': {'name': 'Trader Joes Plaza', 'stopId': 497},
  'Colonnade_Blvd_at_Home_Goods': {'name': 'Colonnade Blvd at Home Goods', 'stopId': 249},
  'Colonnade_Blvd_at_Target/Dicks': {'name': 'Colonnade Blvd at Target/Dicks', 'stopId': 250},
  '215_Blue_Course_Dr_Near_Shell': {'name': '215 Blue Course Dr (Near Shell)', 'stopId': 421},
  'Blue_Course_Dr_at_BB&T_Bank': {'name': 'Blue Course Dr at BB&T Bank', 'stopId': 422},
  'Northland_Center_Outbound': {'name': 'Northland Center Outbound', 'stopId': 423},
  'Northland_Center_Inbound': {'name': 'Northland Center Inbound', 'stopId': 424},
  'Colonnade_Blvd_at_Chicos': {'name': 'Colonnade Blvd at Chicos', 'stopId': 475},
  'Colonnade_Blvd_at_Wegmans': {'name': 'Colonnade Blvd at Wegmans', 'stopId': 476},
  '801_Toftrees_Avenue_-_The_Station': {'name': '801 Toftrees Avenue - The Station', 'stopId': 9},
  'University_Dr_at_the_Pegula_Ice_Arena': {'name': 'University Dr at the Pegula Ice Arena', 'stopId': 150},
  'University_Dr_at_Hastings_Rd': {'name': 'University Dr at Hastings Rd', 'stopId': 151},
  '850_Toftrees_Avenue_-_The_View': {'name': '850 Toftrees Avenue - The View', 'stopId': 251},
  '240_Toftrees_Ave_Turtle_Creek_Apts': {'name': '240 Toftrees Ave (Turtle Creek Apts)', 'stopId': 254},
  'Opposite_301_Toftrees_Ave': {'name': 'Opposite 301 Toftrees Ave', 'stopId': 256},
  '350_Toftrees_Ave_Turtle_Creek_Apts': {'name': '350 Toftrees Ave (Turtle Creek Apts)', 'stopId': 258},
  'Fox_Hollow_Rd_at_Orchard_Rd_Inbound': {'name': 'Fox Hollow Rd at Orchard Rd Inbound', 'stopId': 277},
  'Porter_Rd_at_Beaver_Stadium_East': {'name': 'Porter Rd at Beaver Stadium East', 'stopId': 279},
  'Toftrees_Ave_at_Hillside_and_Fox_Run': {'name': 'Toftrees Ave at Hillside and Fox Run', 'stopId': 319},
  'Toftrees_Ave_at_Wildridge_Apts.': {'name': 'Toftrees Ave at Wildridge Apts.', 'stopId': 326},
  'Curtin_Rd_at_Stadium_West_Parking_Lot': {'name': 'Curtin Rd at Stadium West Parking Lot', 'stopId': 355},
  'Blue_Course_Dr_near_Teaberry_Lane': {'name': 'Blue Course Dr near Teaberry Lane', 'stopId': 425},
  'Havershire_Blvd._across_from_The_Heights': {'name': 'Havershire Blvd. across from The Heights', 'stopId': 428},
  'Havershire_Blvd._at_Northwick_Outbound': {'name': 'Havershire Blvd. at Northwick (Outbound)', 'stopId': 430},
  'Havershire_Blvd._at_Rushcliff_Outbound': {'name': 'Havershire Blvd. at Rushcliff (Outbound)', 'stopId': 431},
  'Vairo_Blvd_at_Vairo_Village_Upper': {'name': 'Vairo Blvd at Vairo Village (Upper)', 'stopId': 503},
  'Vairo_Blvd_at_Vairo_Villagelower': {'name': 'Vairo Blvd at Vairo Village(lower)', 'stopId': 507},
  'Vairo_Blvd_at_Tremont_Outbound': {'name': 'Vairo Blvd at Tremont Outbound', 'stopId': 510},
  'Vairo_Blvd_at_The_Pointe_Outbound': {'name': 'Vairo Blvd at The Pointe Outbound', 'stopId': 512},
  'Vairo_Blvd_at_The_Bryn_Outbound': {'name': 'Vairo Blvd at The Bryn Outbound', 'stopId': 514},
  'Williamsburg_Sq._-_Holiday_Inn/Spring_Hi': {'name': 'Williamsburg Sq. - Holiday Inn/Spring Hi', 'stopId': 516},
  'North_Atherton_Place_at_McDonalds': {'name': 'North Atherton Place at McDonalds', 'stopId': 521},
  '1290_Circleville_Rd': {'name': '1290 Circleville Rd', 'stopId': 624},
  'Circleville_Rd_at_Knob_Hill_Pl': {'name': 'Circleville Rd at Knob Hill Pl', 'stopId': 682},
  'Toftrees_Avenue_near_Alma_Mater_Drive': {'name': 'Toftrees Avenue near Alma Mater Drive', 'stopId': 701},
  'Circleville_Rd_opposite_W_Park_Hills_Ave': {'name': 'Circleville Rd opposite W Park Hills Ave', 'stopId': 711},
  'Oakwood_Ave_at_Copper_Beech_Oakwood': {'name': 'Oakwood Ave at Copper Beech Oakwood', 'stopId': 824},
  'Warner_Blvd_at_Heritage_Run_Office_Ctr': {'name': 'Warner Blvd at Heritage Run Office Ctr', 'stopId': 67},
  '114_Mary_Elizabeth_St': {'name': '114 Mary Elizabeth St', 'stopId': 68},
  'Boalsburg_Pike_at_Pine_Tree_Ave': {'name': 'Boalsburg Pike at Pine Tree Ave', 'stopId': 69},
  'Boalsburg_Pike_at_Shrineview': {'name': 'Boalsburg Pike at Shrineview', 'stopId': 72},
  'Boalsburg_Pike_at_Lee_Ave_Outbound': {'name': 'Boalsburg Pike at Lee Ave (Outbound)', 'stopId': 73},
  'Bear_Meadows_Rd_at_Meadow_Lark_Lane': {'name': 'Bear Meadows Rd at Meadow Lark Lane', 'stopId': 86},
  'Tussey_Mountain': {'name': 'Tussey Mountain', 'stopId': 87},
  'Bear_Meadows_Rd_at_Mount_Pleasant_Dr': {'name': 'Bear Meadows Rd at Mount Pleasant Dr', 'stopId': 88},
  'S_Pugh_St_at_E_College_Ave': {'name': 'S Pugh St at E College Ave', 'stopId': 362},
  'Opposite_240_S_Pugh_St': {'name': 'Opposite 240 S Pugh St', 'stopId': 363},
  '240_S_Pugh_St_Days_Inn': {'name': '240 S Pugh St (Days Inn)', 'stopId': 364},
  'S_Pugh_St_at_E_Nittany_Ave': {'name': 'S Pugh St at E Nittany Ave', 'stopId': 365},
  'S_Pugh_St_at_E_Fairmount_Ave': {'name': 'S Pugh St at E Fairmount Ave', 'stopId': 366},
  'S_Pugh_St_at_E_Hamilton_Ave_Inbound': {'name': 'S Pugh St at E Hamilton Ave Inbound', 'stopId': 367},
  'S_Pugh_St_at_E_Hamilton_Ave_Outbound': {'name': 'S Pugh St at E Hamilton Ave Outbound', 'stopId': 368},
  'S_Pugh_St_at_Waring_Ave': {'name': 'S Pugh St at Waring Ave', 'stopId': 369},
  '909_S_Pugh_St': {'name': '909 S Pugh St', 'stopId': 370},
  '1015_S_Pugh_St': {'name': '1015 S Pugh St', 'stopId': 371},
  '1006_S_Pugh_St': {'name': '1006 S Pugh St', 'stopId': 372},
  'Easterly_Pkwy_at_Old_Boalsburg_Rd': {'name': 'Easterly Pkwy at Old Boalsburg Rd', 'stopId': 373},
  '1218_S_Allen_St': {'name': '1218 S Allen St', 'stopId': 375},
  'S_Pugh_St_at_E_Ellen_Ave': {'name': 'S Pugh St at E Ellen Ave', 'stopId': 376},
  '1248_S_Atherton_St_Citizens_Bank': {'name': '1248 S Atherton St (Citizens Bank)', 'stopId': 377},
  'S_Pugh_St_at_Bradley_Ave': {'name': 'S Pugh St at Bradley Ave', 'stopId': 378},
  '1306_S_Atherton_St': {'name': '1306 S Atherton St', 'stopId': 379},
  'S_Atherton_St_at_Norma_Street': {'name': 'S Atherton St at Norma Street', 'stopId': 380},
  'S_Atherton_St_at_Whitehall_Rd': {'name': 'S Atherton St at Whitehall Rd', 'stopId': 381},
  'S_Atherton_St_at_Science_St': {'name': 'S Atherton St at Science St', 'stopId': 382},
  'Science_St._at_the_Ramada': {'name': 'Science St. at the Ramada', 'stopId': 383},
  'East_Marylyn_Ave_at_Foxdale_Village': {'name': 'East Marylyn Ave at Foxdale Village', 'stopId': 384},
  'Rolling_Ridge_Drive_at_Hills_Plaza': {'name': 'Rolling Ridge Drive at Hills Plaza', 'stopId': 386},
  '301_Rolling_Ridge_Dr_Mt_Nittany_Res': {'name': '301 Rolling Ridge Dr (Mt Nittany Res)', 'stopId': 387},
  'Rolling_Ridge_Dr_at_Hills_Plaza_South': {'name': 'Rolling Ridge Dr at Hills Plaza South', 'stopId': 388},
  'Opposite_383_Rolling_Ridge_Dr': {'name': 'Opposite 383 Rolling Ridge Dr', 'stopId': 389},
  'Opposite_501_Rolling_Ridge_Dr': {'name': 'Opposite 501 Rolling Ridge Dr', 'stopId': 390},
  'Windmere_Dr_at_Wellington_Dr': {'name': 'Windmere Dr at Wellington Dr', 'stopId': 391},
  'Radnor_Rd_at_Regent_Ct': {'name': 'Radnor Rd at Regent Ct', 'stopId': 392},
  'Geisinger_Medical_Center_at_Scenery_Park': {'name': 'Geisinger Medical Center at Scenery Park', 'stopId': 393},
  'Bear_Meadows_Rd_at_Roundhill_Rd_Outbound': {'name': 'Bear Meadows Rd at Roundhill Rd Outbound', 'stopId': 730},
  'Bear_Meadows_Rd_at_Roundhill_Rd_Inbound': {'name': 'Bear Meadows Rd at Roundhill Rd Inbound', 'stopId': 731},
  'Boal_Avenue_Bus_322_at_West_Drive': {'name': 'Boal Avenue (Bus 322) at West Drive', 'stopId': 825},
  'Discovery_Drive_at_Kestrel_Drive': {'name': 'Discovery Drive at Kestrel Drive', 'stopId': 857},
  'Discovery_Drive_at_Wynwood_House': {'name': 'Discovery Drive at Wynwood House', 'stopId': 858},
  'Boal_Avenue_near_Brookside_Drive': {'name': 'Boal Avenue near Brookside Drive', 'stopId': 859},
  'Boal_Avenue_at_Old_Stone_Lane': {'name': 'Boal Avenue at Old Stone Lane', 'stopId': 860},
  'Windmere_Drive_at_Scenery_Court': {'name': 'Windmere Drive at Scenery Court', 'stopId': 861},
  '501_Rolling_Ridge_Drive': {'name': '501 Rolling Ridge Drive', 'stopId': 862},
  '383_Rolling_Ridge_Drive': {'name': '383 Rolling Ridge Drive', 'stopId': 863},
  'Waupelani_Dr_opposite_Jaru_Copy': {'name': 'Waupelani Dr opposite Jaru Copy', 'stopId': 38},
  'Waupelani_Dr_at_Waupelani_Lofts': {'name': 'Waupelani Dr at Waupelani Lofts', 'stopId': 64},
  'Waupelani_Drive_at_OBryan_Lane': {'name': 'Waupelani Drive at OBryan Lane', 'stopId': 329},
  'S_Atherton_near_S_Allen_Street': {'name': 'S Atherton near S Allen Street', 'stopId': 374},
  'S_Atherton_St_at_W_Beaver_Ave_Outbound': {'name': 'S Atherton St at W Beaver Ave Outbound', 'stopId': 394},
  'S_Atherton_Street_at_Highland_Alley': {'name': 'S Atherton Street at Highland Alley', 'stopId': 395},
  'S_Atherton_St_at_Fairmount_Ave_Outbound': {'name': 'S Atherton St at Fairmount Ave Outbound', 'stopId': 396},
  'S_Atherton_St_at_W_Fairmount_Ave_Inbound': {'name': 'S Atherton St at W Fairmount Ave Inbound', 'stopId': 397},
  'S._Atherton_St._at_Pizza_Hut': {'name': 'S. Atherton St. at Pizza Hut', 'stopId': 398},
  '805_S_Atherton_St': {'name': '805 S Atherton St', 'stopId': 399},
  'S_Atherton_St_at_Center_Lane': {'name': 'S Atherton St at Center Lane', 'stopId': 401},
  'Waupelani_Dr_at_S_Allen_St': {'name': 'Waupelani Dr at S Allen St', 'stopId': 402},
  'Waupelani_Dr_at_The_Retreat': {'name': 'Waupelani Dr at The Retreat', 'stopId': 403},
  'Waupelani_Dr_at_Executive_House': {'name': 'Waupelani Dr at Executive House', 'stopId': 406},
  'Waupelani_Dr_at_Lions_Gate_Apts': {'name': 'Waupelani Dr at Lions Gate Apts', 'stopId': 407},
  '445_Waupelani_Dr_Nittany_Gardens': {'name': '445 Waupelani Dr (Nittany Gardens)', 'stopId': 408},
  '450_Waupelani_Dr_Hearthside': {'name': '450 Waupelani Dr (Hearthside)', 'stopId': 409},
  'Waupelani_Dr_at_Southgate_Dr_Inbound': {'name': 'Waupelani Dr at Southgate Dr Inbound', 'stopId': 410},
  'Waupelani_Dr_at_Southgate_Dr_Outbound': {'name': 'Waupelani Dr at Southgate Dr Outbound', 'stopId': 411},
  '712_Southgate_Dr': {'name': '712 Southgate Dr', 'stopId': 412},
  'Southgate_Dr_at_Highlandon_Ct': {'name': 'Southgate Dr at Highlandon Ct', 'stopId': 413},
  'Southgate_Dr_at_Ashwicken_Ct': {'name': 'Southgate Dr at Ashwicken Ct', 'stopId': 414},
  'Southgate_Dr_at_Blue_Course_Dr': {'name': 'Southgate Dr at Blue Course Dr', 'stopId': 415},
  'Stratford_Dr_at_Blue_Course_Dr': {'name': 'Stratford Dr at Blue Course Dr', 'stopId': 416},
  '803_Stratford_Dr': {'name': '803 Stratford Dr', 'stopId': 417},
  'Stratford_Dr_at_Waupelani_Dr': {'name': 'Stratford Dr at Waupelani Dr', 'stopId': 418},
  'Waupelani_Dr._at_Briarwood_Apts': {'name': 'Waupelani Dr. at Briarwood Apts', 'stopId': 732},
  'West_Whitehall_Rd_at_Briarwood': {'name': 'West Whitehall Rd at Briarwood', 'stopId': 856},
  'W_College_Ave_at_Blaise_Alexander': {'name': 'W College Ave at Blaise Alexander', 'stopId': 298},
  'W_College_Ave_at_Airport_Rd': {'name': 'W College Ave at Airport Rd', 'stopId': 299},
  '1795_W_College_Avenue': {'name': '1795 W College Avenue', 'stopId': 300},
  'Opposite_1795_W_College_Ave': {'name': 'Opposite 1795 W College Ave', 'stopId': 301},
  '809_Westerly_Pkwy_Holmes_Foster_Park': {'name': '809 Westerly Pkwy (Holmes Foster Park)', 'stopId': 528},
  '820_Westerly_Pkwy_OLV_Church': {'name': '820 Westerly Pkwy (OLV Church)', 'stopId': 529},
  'Westerly_Pkwy_at_S_Corl_St_Outbound': {'name': 'Westerly Pkwy at S Corl St Outbound', 'stopId': 530},
  'Westerly_Pkwy_at_S_Corl_St_Inbound': {'name': 'Westerly Pkwy at S Corl St Inbound', 'stopId': 531},
  'Westerly_Pkwy_at_Conover_Lane': {'name': 'Westerly Pkwy at Conover Lane', 'stopId': 532},
  'Westerly_Pkwy_opposite_Conover_Ln': {'name': 'Westerly Pkwy opposite Conover Ln', 'stopId': 534},
  'Opposite_1028_Blue_Course': {'name': 'Opposite 1028 Blue Course', 'stopId': 536},
  '1028_Blue_Course_Dr': {'name': '1028 Blue Course Dr', 'stopId': 537},
  '2511_Saratoga_Dr': {'name': '2511 Saratoga Dr', 'stopId': 539},
  '2510_Saratoga_Dr': {'name': '2510 Saratoga Dr', 'stopId': 540},
  'Gwenedd_Lane_at_Charleston_Dr': {'name': 'Gwenedd Lane at Charleston Dr', 'stopId': 541},
  '2237_Gwenedd_Lane': {'name': '2237 Gwenedd Lane', 'stopId': 542},
  'Gwenedd_Lane_at_Autumnwood_Dr_Inbound': {'name': 'Gwenedd Lane at Autumnwood Dr Inbound', 'stopId': 543},
  'Gwenedd_Lane_at_Autumnwood_Dr_Outbound': {'name': 'Gwenedd Lane at Autumnwood Dr Outbound', 'stopId': 544},
  'Autumnwood_Dr_at_Muncy_Rd_Outbound': {'name': 'Autumnwood Dr at Muncy Rd Outbound', 'stopId': 545},
  'Autumnwood_Dr_at_Muncy_Rd_Inbound': {'name': 'Autumnwood Dr at Muncy Rd Inbound', 'stopId': 546},
  'Pine_Hall_Rd_at_Science_Park_Ct_Outbound': {'name': 'Pine Hall Rd at Science Park Ct Outbound', 'stopId': 547},
  'Pine_Hall_Rd_at_Science_Park_Ct_Inbound': {'name': 'Pine Hall Rd at Science Park Ct Inbound', 'stopId': 548},
  '385_Science_Park_Rd_Accuweather': {'name': '385 Science Park Rd (Accuweather)', 'stopId': 553},
  '500_Science_Park_Rd_Chemcut': {'name': '500 Science Park Rd (Chemcut)', 'stopId': 554},
  'Sandy_Dr_at_SPE_Federal_Credit_Union': {'name': 'Sandy Dr at SPE Federal Credit Union', 'stopId': 555},
  'Opposite_2161_Sandy_Dr': {'name': 'Opposite 2161 Sandy Dr', 'stopId': 556},
  'Science_Park_Rd_at_Sandy_Dr_Wonderland': {'name': 'Science Park Rd at Sandy Dr (Wonderland)', 'stopId': 557},
  'Foxpointe_Dr_at_W_Autumnwood_Dr': {'name': 'Foxpointe Dr at W Autumnwood Dr', 'stopId': 728},
  'Foxpointe_Dr_at_E_Autumnwood_Dr': {'name': 'Foxpointe Dr at E Autumnwood Dr', 'stopId': 729},
  'Curtin_Rd_at_McCoy_Natatorium': {'name': 'Curtin Rd at McCoy Natatorium', 'stopId': 148},
  'Curtin_Rd_at_Shields_Building': {'name': 'Curtin Rd at Shields Building', 'stopId': 149},
  '818_Bellaire_Ave_University_Terrace': {'name': '818 Bellaire Ave (University Terrace)', 'stopId': 559},
  'Bellaire_Ave_at_University_Terrace': {'name': 'Bellaire Ave at University Terrace', 'stopId': 560},
  '713_Bellaire_Ave': {'name': '713 Bellaire Ave', 'stopId': 561},
  '718_Bellaire_Ave': {'name': '718 Bellaire Ave', 'stopId': 562},
  'Vairo_Blvd_opposite_Vairo_VillageUpper': {'name': 'Vairo Blvd opposite Vairo Village(Upper)', 'stopId': 504},
  'Vairo_Blvd_opposite_Vairo_Villagelower': {'name': 'Vairo Blvd opposite Vairo Village(lower)', 'stopId': 506},
  'Vairo_Blvd_at_Tremond_Inboundlower': {'name': 'Vairo Blvd at Tremond Inbound(lower)', 'stopId': 508},
  'Vairo_Blvd_at_Tremont_Inbound_upper': {'name': 'Vairo Blvd at Tremont Inbound upper', 'stopId': 509},
  'Vairo_Blvd_at_The_Pointe_Inbound': {'name': 'Vairo Blvd at The Pointe Inbound', 'stopId': 511},
  'Vairo_Blvd_at_The_Bryn_Inbound': {'name': 'Vairo Blvd at The Bryn Inbound', 'stopId': 513},
  'Colonnade_Blvd_Opposite_Kohls': {'name': 'Colonnade Blvd Opposite Kohls', 'stopId': 252},
  'Middle_of_Oakwood_Ave_Outbound': {'name': 'Middle of Oakwood Ave Outbound', 'stopId': 501},
  '658_Oakwood_Ave': {'name': '658 Oakwood Ave', 'stopId': 502},
  'Oakwood_Ave_at_Texas_Roadhouse': {'name': 'Oakwood Ave at Texas Roadhouse', 'stopId': 517},
  'Middle_of_Oakwood_Ave_Inbound': {'name': 'Middle of Oakwood Ave Inbound', 'stopId': 518},
  'Oakwood_Ave_at_Benjamin_Ct': {'name': 'Oakwood Ave at Benjamin Ct', 'stopId': 519},
  'North_Atherton_Place_at_Walmart': {'name': 'North Atherton Place at Walmart', 'stopId': 520},
  'Vairo_Blvd_at_North_Atherton_Place': {'name': 'Vairo Blvd at North Atherton Place', 'stopId': 704},
  '972_Oakwood_Ave': {'name': '972 Oakwood Ave', 'stopId': 709},
  'Opposite_972_Oakwood_Ave': {'name': 'Opposite 972 Oakwood Ave', 'stopId': 710},
  'Oakwood_Ave_at_Vairo_Village_Comm_Ctr': {'name': 'Oakwood Ave at Vairo Village Comm Ctr', 'stopId': 714},
  '545_Oakwood_Ave_Copper_Beech_Oakwood': {'name': '545 Oakwood Ave (Copper Beech Oakwood)', 'stopId': 715},
  'Colonnade_Blvd_at_Kohls': {'name': 'Colonnade Blvd at Kohls', 'stopId': 761},
  'Opposite_240_Toftrees_Ave': {'name': 'Opposite 240 Toftrees Ave', 'stopId': 253},
  '301_Toftrees_Ave': {'name': '301 Toftrees Ave', 'stopId': 255},
  '359_Toftrees_Ave_Parkgate_Apartments': {'name': '359 Toftrees Ave (Parkgate Apartments)', 'stopId': 257},
  'Oakwood_Ave_at_Vairo_Blvd': {'name': 'Oakwood Ave at Vairo Blvd', 'stopId': 276},
  'Fox_Hollow_Rd_at_Orchard_Rd_Outbound': {'name': 'Fox Hollow Rd at Orchard Rd Outbound', 'stopId': 278},
  'Porter_Rd_at_the_Visitors_Center': {'name': 'Porter Rd at the Visitors Center', 'stopId': 280},
  'Curtin_Rd_at_Bryce_Jordan_Center': {'name': 'Curtin Rd at Bryce Jordan Center', 'stopId': 287},
  'Blue_Course_Dr_at_Blue_Course_Commons': {'name': 'Blue Course Dr at Blue Course Commons', 'stopId': 426},
  'Havershire_Blvd._at_The_Heights': {'name': 'Havershire Blvd. at The Heights', 'stopId': 427},
  'Havershire_Blvd._at_Northwick_Inbound': {'name': 'Havershire Blvd. at Northwick (Inbound)', 'stopId': 429},
  'Havershire_Blvd._at_Rushcliff_Inbound': {'name': 'Havershire Blvd. at Rushcliff (Inbound)', 'stopId': 432},
  '1381_Circleville_Road': {'name': '1381 Circleville Road', 'stopId': 625},
  'Toftrees_Avenue_near_Beaumanor_Drive': {'name': 'Toftrees Avenue near Beaumanor Drive', 'stopId': 700},
  'Circleville_Rd_at_W_Park_Hills_Ave': {'name': 'Circleville Rd at W Park Hills Ave', 'stopId': 703},
  'Circleville_Rd_at_E_Park_Hills_Ave': {'name': 'Circleville Rd at E Park Hills Ave', 'stopId': 708},
  'Toftrees_Ave_at_Squirel_Run_Apts.': {'name': 'Toftrees Ave at Squirel Run Apts.', 'stopId': 712},
  'Toftrees_Ave_at_the_Carnegie_Inn_and_Spa': {'name': 'Toftrees Ave at the Carnegie Inn and Spa', 'stopId': 713},
  'Galen_Drive_at_Haverford_Circle': {'name': 'Galen Drive at Haverford Circle', 'stopId': 405},
  'Circleville_Rd_at_Farmstead_Lane_Inbound': {'name': 'Circleville Rd at Farmstead Lane Inbound', 'stopId': 433},
  'Circleville_Rd_at_Farmstead_Ln_Outbound': {'name': 'Circleville Rd at Farmstead Ln Outbound', 'stopId': 434},
  'Valley_Vista_Dr_at_Oak_Hill_Apts_Oubound': {'name': 'Valley Vista Dr at Oak Hill Apts Oubound', 'stopId': 435},
  'Valley_Vista_Dr_at_Oak_Hill_Apts_Inbound': {'name': 'Valley Vista Dr at Oak Hill Apts Inbound', 'stopId': 436},
  'Valley_Vista_Dr_at_Bachman_Lane_Outbound': {'name': 'Valley Vista Dr at Bachman Lane Outbound', 'stopId': 437},
  'Valley_Vista_Dr_at_Bachman_Lane_Inbound': {'name': 'Valley Vista Dr at Bachman Lane Inbound', 'stopId': 438},
  'Valley_Vista_at_Devonshire_Outbound': {'name': 'Valley Vista at Devonshire Outbound', 'stopId': 439},
  'Valley_Vista_Dr_at_Devonshire_Inbound': {'name': 'Valley Vista Dr at Devonshire Inbound', 'stopId': 440},
  'Valley_Vista_at_Oakley_Dr_Inbound': {'name': 'Valley Vista at Oakley Dr Inbound', 'stopId': 448},
  'Amblewood_Way_at_School_Drive': {'name': 'Amblewood Way at School Drive', 'stopId': 461},
  'Galen_Dr_at_Amblewood_Way': {'name': 'Galen Dr at Amblewood Way', 'stopId': 464},
  '741_Galen_Dr': {'name': '741 Galen Dr', 'stopId': 466},
  'Carnegie_Dr_at_Vista_Lofts': {'name': 'Carnegie Dr at Vista Lofts', 'stopId': 467},
  'Carnegie_Drivea_at_Valley_Vista_Drive': {'name': 'Carnegie Drivea at Valley Vista Drive', 'stopId': 468},
  'Valley_Vista_Dr_at_Oakley_Dr_Inbound': {'name': 'Valley Vista Dr at Oakley Dr Inbound', 'stopId': 483},
  'Geisinger_Grays_Woods': {'name': 'Geisinger Grays Woods', 'stopId': 738},
  '2520_Green_Tech_Dr._at_CVIM': {'name': '2520 Green Tech Dr. at CVIM', 'stopId': 830},
  'Green_Tech_Dr._at_Center_for_Dermatology': {'name': 'Green Tech Dr. at Center for Dermatology', 'stopId': 831},
  'Nittany_Mall_Main_Entrance': {'name': 'Nittany Mall Main Entrance', 'stopId': 165},
  'Nittany_Mall_near_Macys': {'name': 'Nittany Mall near Macys', 'stopId': 311},
  'E_College_Ave_at_Woskob_Industrial_Park': {'name': 'E College Ave at Woskob Industrial Park', 'stopId': 327},
  '2601_E_College_Ave': {'name': '2601 E College Ave', 'stopId': 328},
  'E_College_Ave_at_Struble_Rd': {'name': 'E College Ave at Struble Rd', 'stopId': 330},
  'E_College_Ave_at_Nittany_Commons': {'name': 'E College Ave at Nittany Commons', 'stopId': 331},
  'E_College_Ave_opp_Nittany_Commons': {'name': 'E College Ave opp Nittany Commons', 'stopId': 332},
  'E_College_Ave_at_Limerock_Terrace': {'name': 'E College Ave at Limerock Terrace', 'stopId': 333},
  'S_Parkview_Blvd_at_Zion_Rd_Inbound': {'name': 'S Parkview Blvd at Zion Rd Inbound', 'stopId': 578},
  'S_Parkview_Blvd_at_Zion_Rd_Outbound': {'name': 'S Parkview Blvd at Zion Rd Outbound', 'stopId': 579},
  '1042_E_High_St': {'name': '1042 E High St', 'stopId': 580},
  '1043_E_High_St': {'name': '1043 E High St', 'stopId': 581},
  '953_E_High_St': {'name': '953 E High St', 'stopId': 582},
  '960A_E_High_St': {'name': '960A E High St', 'stopId': 583},
  'E_High_St_at_S_School_St': {'name': 'E High St at S School St', 'stopId': 590},
  'E_High_St_at_N_School_St': {'name': 'E High St at N School St', 'stopId': 591},
  '804_E_High_St': {'name': '804 E High St', 'stopId': 592},
  '805_E_High_St': {'name': '805 E High St', 'stopId': 593},
  '220_N_McAllister_St': {'name': '220 N McAllister St', 'stopId': 594},
  '211_N_McAllister_St': {'name': '211 N McAllister St', 'stopId': 595},
  '1026_Benner_Pike': {'name': '1026 Benner Pike', 'stopId': 661},
  '1015_Benner_Pike': {'name': '1015 Benner Pike', 'stopId': 662},
  'Opposite_1317_Benner_Pike': {'name': 'Opposite 1317 Benner Pike', 'stopId': 663},
  '1317_Benner_Pike': {'name': '1317 Benner Pike', 'stopId': 664},
  'Centre_County_Correctional_Facility': {'name': 'Centre County Correctional Facility', 'stopId': 665},
  'Opposite_2780_Benner_Pike': {'name': 'Opposite 2780 Benner Pike', 'stopId': 667},
  '2780_Benner_Pike': {'name': '2780 Benner Pike', 'stopId': 668},
  'Benner_Pike_at_Centre_Peace': {'name': 'Benner Pike at Centre Peace', 'stopId': 669},
  'Benner_Pike_at_Rolling_Ridge_Rd_Outbound': {'name': 'Benner Pike at Rolling Ridge Rd Outbound', 'stopId': 670},
  'Benner_Pike_at_Quarry_St': {'name': 'Benner Pike at Quarry St', 'stopId': 671},
  'Benner_Pike_at_Butler_Lane': {'name': 'Benner Pike at Butler Lane', 'stopId': 672},
  'Benner_Pike_at_Bel_Air_Hills_Rd': {'name': 'Benner Pike at Bel Air Hills Rd', 'stopId': 673},
  '3482_Benner_Pike': {'name': '3482 Benner Pike', 'stopId': 674},
  'Willowbank_St_at_Walnut_St': {'name': 'Willowbank St at Walnut St', 'stopId': 675},
  'Willowbank_St_at_W_Water_St': {'name': 'Willowbank St at W Water St', 'stopId': 676},
  'Willowbank_St_at_Valentine_Hill_Rd': {'name': 'Willowbank St at Valentine Hill Rd', 'stopId': 677},
  'Willowbank_St_at_Mill_St': {'name': 'Willowbank St at Mill St', 'stopId': 678},
  'W_High_St_at_S_Allegheny_St': {'name': 'W High St at S Allegheny St', 'stopId': 679},
  'West_High_St_at_the_YMCA': {'name': 'West High St at the YMCA', 'stopId': 680},
  'N_Allegheny_St_at_E_High_St_Confers': {'name': 'N Allegheny St at E High St (Confers)', 'stopId': 681},
  'N_Allegheny_St_at_E_Howard_St': {'name': 'N Allegheny St at E Howard St', 'stopId': 683},
  'N_Allegheny_St_at_W_Lamb_St': {'name': 'N Allegheny St at W Lamb St', 'stopId': 684},
  'N_Allegheny_St_at_E_Linn_St': {'name': 'N Allegheny St at E Linn St', 'stopId': 685},
  'E_Linn_St_at_N_Ridge_St_Inbound': {'name': 'E Linn St at N Ridge St Inbound', 'stopId': 686},
  'E_Linn_St_at_N_Ridge_St_Outbound': {'name': 'E Linn St at N Ridge St Outbound', 'stopId': 687},
  'E_Linn_St_at_Armor_St_Outbound': {'name': 'E Linn St at Armor St Outbound', 'stopId': 688},
  'E_Linn_St_at_Armor_St_Inbound': {'name': 'E Linn St at Armor St Inbound', 'stopId': 689},
  'E_Linn_St_at_N_Wilson_St_Inbound': {'name': 'E Linn St at N Wilson St Inbound', 'stopId': 690},
  'E_Linn_St_at_N_Wilson_St_Outbound': {'name': 'E Linn St at N Wilson St Outbound', 'stopId': 691},
  'N_Wilson_St_at_E_Lamb_St_Outbound': {'name': 'N Wilson St at E Lamb St Outbound', 'stopId': 692},
  'N_Wilson_St_at_E_Lamb_St_Inbound': {'name': 'N Wilson St at E Lamb St Inbound', 'stopId': 693},
  'Howard_St_at_Monroe_St': {'name': 'Howard St at Monroe St', 'stopId': 694},
  'Howard_St_at_Centre_Crest': {'name': 'Howard St at Centre Crest', 'stopId': 695},
  'N_Allegheny_St_at_W_Howard_St': {'name': 'N Allegheny St at W Howard St', 'stopId': 696},
  '2932_Benner_Pike': {'name': '2932 Benner Pike', 'stopId': 706},
  '2903_Benner_Pike': {'name': '2903 Benner Pike', 'stopId': 707},
  'Benner_Pike_at_Barnes_and_Noble': {'name': 'Benner Pike at Barnes and Noble', 'stopId': 745},
  'East_College_Ave_at_Green_Acres_Lane': {'name': 'East College Ave at Green Acres Lane', 'stopId': 753},
  'East_College_Avenue_at_Grandview_Road': {'name': 'East College Avenue at Grandview Road', 'stopId': 754},
  'Benner_Pike_Opposite_Ellis_Lane': {'name': 'Benner Pike Opposite Ellis Lane', 'stopId': 762},
  '1225_Benner_Pk': {'name': '1225 Benner Pk', 'stopId': 763},
  'East_College_Ave_at_Citi_Clean': {'name': 'East College Ave at Citi Clean', 'stopId': 809},
  'Benner_Pike_near_Stonecrest_Dr': {'name': 'Benner Pike near Stonecrest Dr', 'stopId': 817},
  'Benner_Pike_opposite_Stonecrest_Dr': {'name': 'Benner Pike opposite Stonecrest Dr', 'stopId': 818},
  'Zion_Road_at_Centre_Street': {'name': 'Zion Road at Centre Street', 'stopId': 850},
  'Weis_Market': {'name': 'Weis Market', 'stopId': 851},
  'Zion_Road_at_Park_Pl_Kish_Bank': {'name': 'Zion Road at Park Pl (Kish Bank)', 'stopId': 852},
  '310_North_Harrison_Road': {'name': '310 North Harrison Road', 'stopId': 19},
  'opposite_310_North_Harrison_Road': {'name': 'opposite 310 North Harrison Road', 'stopId': 24},
  'Nittany_Mall_Sears_Auto': {'name': 'Nittany Mall (Sears Auto)', 'stopId': 320},
  'Governors_Gate_Apartments': {'name': 'Governors Gate Apartments', 'stopId': 573},
  'Opposite_291_Governors_Park_Rd': {'name': 'Opposite 291 Governors Park Rd', 'stopId': 574},
  '291_Governors_Park_Rd': {'name': '291 Governors Park Rd', 'stopId': 575},
  'Opposite_1001_Airport_Rd': {'name': 'Opposite 1001 Airport Rd', 'stopId': 576},
  '1001_Airport_Rd': {'name': '1001 Airport Rd', 'stopId': 577},
  'E_Bishop_St_across_from_PennDOT_office': {'name': 'E Bishop St across from PennDOT office', 'stopId': 584},
  'East_Bishop_St_at_Beaver_Farm_Lane': {'name': 'East Bishop St at Beaver Farm Lane', 'stopId': 585},
  'E_Bishop_St_at_the_Burger_King': {'name': 'E Bishop St at the Burger King', 'stopId': 586},
  'E_Bishop_St_at_Bellefonte_High_School': {'name': 'E Bishop St at Bellefonte High School', 'stopId': 587},
  'E_Bishop_St_at_High_Sch_Football_field': {'name': 'E Bishop St at High Sch Football field', 'stopId': 588},
  'E_Bishop_St_at_S_McAllister_St': {'name': 'E Bishop St at S McAllister St', 'stopId': 589},
  'E_Bishop_St_at_S_Wilson_St': {'name': 'E Bishop St at S Wilson St', 'stopId': 596},
  'E_Bishop_St_at_Shope_St': {'name': 'E Bishop St at Shope St', 'stopId': 597},
  'E_Bishop_St_at_Badger_Lane': {'name': 'E Bishop St at Badger Lane', 'stopId': 598},
  'E_Bishop_St_at_Blanchard_St': {'name': 'E Bishop St at Blanchard St', 'stopId': 599},
  'Blanchard_St_at_E_Crawford_Lane_Inbound': {'name': 'Blanchard St at E Crawford Lane Inbound', 'stopId': 600},
  'Blanchard_St_at_E_Crawford_Lane_Outbound': {'name': 'Blanchard St at E Crawford Lane Outbound', 'stopId': 601},
  'Blanchard_St_at_Humes_Rd': {'name': 'Blanchard St at Humes Rd', 'stopId': 602},
  'Blanchard_St_at_Union_Rd': {'name': 'Blanchard St at Union Rd', 'stopId': 603},
  'Opposite_614_Blanchard_St': {'name': 'Opposite 614 Blanchard St', 'stopId': 604},
  '608_Blanchard_St': {'name': '608 Blanchard St', 'stopId': 605},
  '724_Blanchard_St': {'name': '724 Blanchard St', 'stopId': 606},
  'Blanchard_St_at_Spring_Brae_Ct': {'name': 'Blanchard St at Spring Brae Ct', 'stopId': 607},
  '1309_Blanchard_St': {'name': '1309 Blanchard St', 'stopId': 608},
  'Opposite_1309_Blanchard_St': {'name': 'Opposite 1309 Blanchard St', 'stopId': 609},
  'N_Harrison_Rd_at_Weaver_Hill_Rd_Inbound': {'name': 'N Harrison Rd at Weaver Hill Rd Inbound', 'stopId': 610},
  'N_Harrison_Rd_at_Weaver_Hill_Rd_Outbound': {'name': 'N Harrison Rd at Weaver Hill Rd Outbound', 'stopId': 611},
  '668_N_Harrison_Rd': {'name': '668 N Harrison Rd', 'stopId': 612},
  'N_Harrison_Rd_at_Limestone_Dr': {'name': 'N Harrison Rd at Limestone Dr', 'stopId': 613},
  'N_Harrison_Rd_at_Central_PA_Institute': {'name': 'N Harrison Rd at Central PA Institute', 'stopId': 614},
  'N_Harrison_Rd_at_Supelco/Sigma_Aldrich': {'name': 'N Harrison Rd at Supelco/Sigma Aldrich', 'stopId': 615},
  'N_Harrison_Rd_at_GE-MAR_Ave_Outbound': {'name': 'N Harrison Rd at GE-MAR Ave Outbound', 'stopId': 616},
  'N_Harrison_Rd_at_GE-MAR_Ave_Inbound': {'name': 'N Harrison Rd at GE-MAR Ave Inbound', 'stopId': 617},
  '129_Harrison_Rd': {'name': '129 Harrison Rd', 'stopId': 618},
  '136_Harrison_Rd': {'name': '136 Harrison Rd', 'stopId': 619},
  '218_Harrison_Rd': {'name': '218 Harrison Rd', 'stopId': 620},
  'Harrison_Rd_at_Jodon_Ave': {'name': 'Harrison Rd at Jodon Ave', 'stopId': 621},
  'S_Main_St_at_Sunset_Ave': {'name': 'S Main St at Sunset Ave', 'stopId': 622},
  'Sunset_Ave_at_S_Main_St': {'name': 'Sunset Ave at S Main St', 'stopId': 623},
  'South_Main_St_at_Jodon_Ave': {'name': 'South Main St at Jodon Ave', 'stopId': 626},
  'South_Main_St_at_Whiterock_Ave': {'name': 'South Main St at Whiterock Ave', 'stopId': 627},
  'S_Main_St_at_Bilger_Ave_Outbound': {'name': 'S Main St at Bilger Ave Outbound', 'stopId': 628},
  'S_Main_St_at_Bilger_Ave_Inbound': {'name': 'S Main St at Bilger Ave Inbound', 'stopId': 629},
  'S_Main_St_at_Griffith_Lane_Inbound': {'name': 'S Main St at Griffith Lane Inbound', 'stopId': 630},
  'S_Main_St_at_Griffith_Lane_Outbound': {'name': 'S Main St at Griffith Lane Outbound', 'stopId': 631},
  'N_Main_St_at_W_College_Ave': {'name': 'N Main St at W College Ave', 'stopId': 632},
  '105_N_Main_St': {'name': '105 N Main St', 'stopId': 633},
  'N_Main_St_at_Mack_Ave_Outbound': {'name': 'N Main St at Mack Ave Outbound', 'stopId': 634},
  'N_Main_St_at_Mack_Ave_Inbound': {'name': 'N Main St at Mack Ave Inbound', 'stopId': 635},
  'Melanie_Ln_at_Danielle_Dr': {'name': 'Melanie Ln at Danielle Dr', 'stopId': 636},
  'Melanie_Ln_at_Vanessa_Dr': {'name': 'Melanie Ln at Vanessa Dr', 'stopId': 637},
  'Vanessa_Dr_at_Tealbriar_Dr': {'name': 'Vanessa Dr at Tealbriar Dr', 'stopId': 638},
  'Gwenedd_Lane_at_Steeplechase_Dr': {'name': 'Gwenedd Lane at Steeplechase Dr', 'stopId': 639},
  'Steeplechase_Dr_at_Tealbriar_Lane': {'name': 'Steeplechase Dr at Tealbriar Lane', 'stopId': 640},
  '102_Steeplechase_Dr': {'name': '102 Steeplechase Dr', 'stopId': 641},
  '128/132_West_College_Ave': {'name': '128/132 West College Ave', 'stopId': 642},
  'West_College_Ave_at_Norman_Ave': {'name': 'West College Ave at Norman Ave', 'stopId': 643},
  '200_W_College_Ave': {'name': '200 W College Ave', 'stopId': 644},
  '211_W_College_Ave': {'name': '211 W College Ave', 'stopId': 645},
  'W_College_Ave_at_Breons_Lane': {'name': 'W College Ave at Breons Lane', 'stopId': 646},
  'W_College_Ave_at_Robinson_Lane': {'name': 'W College Ave at Robinson Lane', 'stopId': 647},
  'Opposite_550_W_College_Ave': {'name': 'Opposite 550 W College Ave', 'stopId': 648},
  '550_W_College_Ave': {'name': '550 W College Ave', 'stopId': 649},
  'W_College_Ave_opposite_Drivers_Exam_Ctr': {'name': 'W College Ave opposite Drivers Exam Ctr', 'stopId': 650},
  'W_College_Ave_at_Drivers_Exam_Center': {'name': 'W College Ave at Drivers Exam Center', 'stopId': 651},
  'W_College_Ave_at_Peru_Circle_Inbound': {'name': 'W College Ave at Peru Circle Inbound', 'stopId': 652},
  'W_College_Ave_at_Peru_Circle_Outbound': {'name': 'W College Ave at Peru Circle Outbound', 'stopId': 653},
  'E_College_Ave_at_Transfer_Rd_Outbound': {'name': 'E College Ave at Transfer Rd Outbound', 'stopId': 654},
  'E_College_Ave_at_Transfer_Rd_Inbound': {'name': 'E College Ave at Transfer Rd Inbound', 'stopId': 655},
  'East_College_Ave_at_Summit_Park': {'name': 'East College Ave at Summit Park', 'stopId': 656},
  '3400_East_College_Avenue': {'name': '3400 East College Avenue', 'stopId': 658},
  '3315_E_College_Ave': {'name': '3315 E College Ave', 'stopId': 659},
  'Shiloh_Rd_at_Nittany_Mall_Sears': {'name': 'Shiloh Rd at Nittany Mall (Sears)', 'stopId': 660},
  'Bishop_St_at_Grand_Rental_Station': {'name': 'Bishop St at Grand Rental Station', 'stopId': 750},
  'Opposite_1068_Zion_St': {'name': 'Opposite 1068 Zion St', 'stopId': 751},
  '244/248_Gwenedd_Lane': {'name': '244/248 Gwenedd Lane', 'stopId': 842},
  'Porter_Rd_at_Jordan_East_Parking': {'name': 'Porter Rd at Jordan East Parking', 'stopId': 281},
  'Mount_Nittany_Medical_Center': {'name': 'Mount Nittany Medical Center', 'stopId': 351},
  'Centre_Med_Science_Bldg': {'name': 'Centre Med Science Bldg', 'stopId': 352},
  'Park_Ave_at_Orchard_Rd_Westbound': {'name': 'Park Ave at Orchard Rd Westbound', 'stopId': 353},
  'Park_Ave_at_Orchard_Rd_Eastbound': {'name': 'Park Ave at Orchard Rd Eastbound', 'stopId': 354},
  'Innovation_Blvd_at_Penn_Stater_Conf_Ctr': {'name': 'Innovation Blvd at Penn Stater Conf Ctr', 'stopId': 566},
  'Innovation_Blvd_at_Lubert_Building': {'name': 'Innovation Blvd at Lubert Building', 'stopId': 567},
  'Porter_Rd_at_Medlar_Field': {'name': 'Porter Rd at Medlar Field', 'stopId': 569},
  'White_Course_Dr_at_Red_A_Parking_Lot': {'name': 'White Course Dr at Red A Parking Lot', 'stopId': 570},
  'White_Course_Dr_at_Earth-Eng_Sci_Bldg': {'name': 'White Course Dr at Earth-Eng Sci Bldg', 'stopId': 571},
  'White_Course_Dr_at_Dunham_Hall': {'name': 'White Course Dr at Dunham Hall', 'stopId': 572},
  'Innovation_Blvd_at_331_Bldg': {'name': 'Innovation Blvd at 331 Bldg', 'stopId': 757},
  'Innovation_Blvd_at_Materials_Research': {'name': 'Innovation Blvd at Materials Research', 'stopId': 758},
  'Innovation_Blvd_at_Outreach_Building': {'name': 'Innovation Blvd at Outreach Building', 'stopId': 759},
  'Hastings_Rd_at_University_Drive': {'name': 'Hastings Rd at University Drive', 'stopId': 5},
  'Bigler_Rd_at_Nittany_Community_Center': {'name': 'Bigler Rd at Nittany Community Center', 'stopId': 159},
  'Hastings_Rd_at_Lot_83_East': {'name': 'Hastings Rd at Lot 83 East', 'stopId': 282},
  'Hastings_Rd_at_Forest_Research_Lab': {'name': 'Hastings Rd at Forest Research Lab', 'stopId': 283},
  'Walmart_-_Inbound': {'name': 'Walmart - Inbound', 'stopId': 163},
  'Ross/Bed_Bath_&_Beyond': {'name': 'Ross/Bed Bath & Beyond', 'stopId': 164},
  'Villas_at_Happy_Valley': {'name': 'Villas at Happy Valley', 'stopId': 166},
  'Sams_Club': {'name': 'Sams Club', 'stopId': 259},
  'Cricklewood_Dr_at_N_Barkway_Lane': {'name': 'Cricklewood Dr at N Barkway Lane', 'stopId': 260},
  'Cricklewood_Dr_at_S_Barkway_Lane': {'name': 'Cricklewood Dr at S Barkway Lane', 'stopId': 261},
  'Cricklewood_Dr_at_Wilts_Lane_Outbound': {'name': 'Cricklewood Dr at Wilts Lane Outbound', 'stopId': 262},
  'Cricklewood_Dr_at_Wilts_Lane_Inbound': {'name': 'Cricklewood Dr at Wilts Lane Inbound', 'stopId': 263},
  '541_Cricklewood_Dr': {'name': '541 Cricklewood Dr', 'stopId': 264},
  '711_Cricklewood_Dr': {'name': '711 Cricklewood Dr', 'stopId': 265},
  'Opposite_711_Cricklewood_Dr': {'name': 'Opposite 711 Cricklewood Dr', 'stopId': 266},
  'Cricklewood_Dr_at_the_American_Ale_House': {'name': 'Cricklewood Dr at the American Ale House', 'stopId': 267},
  'Cricklewood_Dr_at_Cricklewood_Apts': {'name': 'Cricklewood Dr at Cricklewood Apts', 'stopId': 268},
  'Opposite_910_Cricklewood_Dr': {'name': 'Opposite 910 Cricklewood Dr', 'stopId': 269},
  '910_Cricklewood_Dr': {'name': '910 Cricklewood Dr', 'stopId': 270},
  'Presidents_Dr_at_Varsity_Lane_Inbound': {'name': 'Presidents Dr at Varsity Lane Inbound', 'stopId': 271},
  'Presidents_Dr_at_Varsity_Lane_Outbound': {'name': 'Presidents Dr at Varsity Lane Outbound', 'stopId': 272},
  'Village_at_Penn_State_Inbound': {'name': 'Village at Penn State Inbound', 'stopId': 273},
  'Village_at_Penn_State_Outbound': {'name': 'Village at Penn State Outbound', 'stopId': 274},
  'Cricklewood_Dr_at_Cricklewood_Circle': {'name': 'Cricklewood Dr at Cricklewood Circle', 'stopId': 275},
  'Village_at_Penn_State_-_Atrium_Outbound': {'name': 'Village at Penn State - Atrium Outbound', 'stopId': 286},
  'Village_at_Penn_State_-_Atrium_Inbound': {'name': 'Village at Penn State - Atrium Inbound', 'stopId': 309},
  '200_Shiloh_Rd': {'name': '200 Shiloh Rd', 'stopId': 321},
  'Premiere_Dr_at_the_UEC_12_Theatre': {'name': 'Premiere Dr at the UEC 12 Theatre', 'stopId': 322},
  'Dreibelbis_St_at_the_Summit_at_Shiloh': {'name': 'Dreibelbis St at the Summit at Shiloh', 'stopId': 324},
  'Pike_St_at_Limerock_Terrace_Inbound': {'name': 'Pike St at Limerock Terrace Inbound', 'stopId': 334},
  'Pike_St_at_Limerock_Terrace_Outbound': {'name': 'Pike St at Limerock Terrace Outbound', 'stopId': 335},
  'Pike_St_at_Hickory_Lane_Inbound': {'name': 'Pike St at Hickory Lane Inbound', 'stopId': 336},
  'Pike_St_at_Hickory_Lane_Outbound': {'name': 'Pike St at Hickory Lane Outbound', 'stopId': 337},
  '542_Pike_St': {'name': '542 Pike St', 'stopId': 338},
  '537_Pike_St': {'name': '537 Pike St', 'stopId': 339},
  'Pike_St_at_Dale_St_Outbound': {'name': 'Pike St at Dale St Outbound', 'stopId': 340},
  'Pike_St_at_Dale_St_Inbound': {'name': 'Pike St at Dale St Inbound', 'stopId': 341},
  'Pike_St_at_Mary_St_Inbound': {'name': 'Pike St at Mary St Inbound', 'stopId': 342},
  'Pike_St_at_Mary_St_Outbound': {'name': 'Pike St at Mary St Outbound', 'stopId': 343},
  'Elmwood_St_at_Elm_St': {'name': 'Elmwood St at Elm St', 'stopId': 344},
  '700_Elmwood_St': {'name': '700 Elmwood St', 'stopId': 345},
  'Elmwood_St_at_Clover_Rd': {'name': 'Elmwood St at Clover Rd', 'stopId': 346},
  'Elmwood_St_at_Hillview_Ave': {'name': 'Elmwood St at Hillview Ave', 'stopId': 347},
  '200_Elmwood_St': {'name': '200 Elmwood St', 'stopId': 348},
  '201_Elmwood_St': {'name': '201 Elmwood St', 'stopId': 349},
  'Sams_Club_entrance_driveway': {'name': 'Sams Club entrance driveway', 'stopId': 666},
  'Woodledge_Dr_Inbound_To_Campus': {'name': 'Woodledge Dr Inbound (To Campus)', 'stopId': 755},
  'Woodledge_Dr_Outbound_To_Toftrees': {'name': 'Woodledge Dr Outbound (To Toftrees)', 'stopId': 756},
  'Dreibelbis_St_at_Independence_Place': {'name': 'Dreibelbis St at Independence Place', 'stopId': 764},
  '125-127_Presidents_Dr': {'name': '125-127 Presidents Dr', 'stopId': 819},
  'Presidents_Dr_at_Tradition_Dr': {'name': 'Presidents Dr at Tradition Dr', 'stopId': 820},
  '115_Premiere_Dr_Best_Western': {'name': '115 Premiere Dr (Best Western)', 'stopId': 822},
  'Woodledge_Dr_at_Woodledge_Circle': {'name': 'Woodledge Dr at Woodledge Circle', 'stopId': 832},
  'Woodledge_Dr_opposite_Woodledge_Circle': {'name': 'Woodledge Dr opposite Woodledge Circle', 'stopId': 833},
  '323_Easterly_Pkwy': {'name': '323 Easterly Pkwy', 'stopId': 716},
  '233_Easterly_Pkwy': {'name': '233 Easterly Pkwy', 'stopId': 717},
  'Easterly_Pkwy_at_Garner_St': {'name': 'Easterly Pkwy at Garner St', 'stopId': 718},
  '234_Easterly_Pkwy_Easterly_Pkwy_Elem': {'name': '234 Easterly Pkwy (Easterly Pkwy Elem)', 'stopId': 719},
  '1245_S_Atherton_St_Happy_Vly_Motor_Inn': {'name': '1245 S Atherton St (Happy Vly Motor Inn)', 'stopId': 720},
  '1450_S_Atherton_St_Ramada_Inn': {'name': '1450 S Atherton St (Ramada Inn)', 'stopId': 721},
  '1550_S_Atherton_St_Courtyd_by_Marriott': {'name': '1550 S Atherton St (Courtyd by Marriott)', 'stopId': 722},
  'Opposite_474_Windmere_Dr': {'name': 'Opposite 474 Windmere Dr', 'stopId': 723},
  'Opposite_428_Windmere_Dr': {'name': 'Opposite 428 Windmere Dr', 'stopId': 724},
  '123_Rolling_Ridge_Dr': {'name': '123 Rolling Ridge Dr', 'stopId': 725},
  'University_Drive_at_Jordan_Center_Gate_A': {'name': 'University Drive at Jordan Center Gate A', 'stopId': 726}
};
